### ISSUE TITLE
Broken "Events" block layout in handbook/tools/google-calendar/ (large desktop resolution)

### ISSUE THREAD

**Issue by beltranrengifo** [liferay-design/liferay.design#1007]
**Describe the bug**
For large screen resolution (1281px & up), Event block layout is broken

**To Reproduce**

1. Go to https://liferay.design/handbook/tools/google-calendar/
2. Scroll down to 'Events'
3. See error

**Expected behavior**
This block renders same layout than other blocks in the page

**Screenshots**
Chrome
![image](https://user-images.githubusercontent.com/19485114/125585774-514f5017-3c8f-4c3e-b2ec-fd99f96883dc.png)
Firefox
![image](https://user-images.githubusercontent.com/19485114/125586293-7abb2b00-35d6-4ad2-b54d-9470128a6c28.png)

**Desktop (please complete the following information):**

-   OS: OSX 11.4
-   Browser: Chrome. Safari and Firefox break the text block to a new row
-   Version: last versions on Mac

**Comment by plhnk** [comment]
thanks for opening this @beltranrengifo!
