### ISSUE TITLE
Links are broken on blueprints

### ISSUE THREAD

**Issue by YoshikazuShimizu** [liferay-design/liferay.design#1014]
Links to Iconography and Illustrations are broken: https://liferay.design/blueprints/resources/iconography/
Could you check all links please?

Thanks,
Yoshi

**Comment by plhnk** [comment]
fixed in #1046

**Comment by plhnk** [comment]
thanks for reporting @YoshikazuShimizu — and thanks for bearing with us as we took time to fix!
