### ISSUE TITLE
User email is not possible to read on user dropdown

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#110]
**Describe the bug**
The user email is not possible to read in the user dropdown due to not enough contrast between the background color and the font-color

**To Reproduce**
1. Login
2. Click on user face

**Expected behavior**
Enough contrast at least or another solution for it :)

**Screenshots**
![image](https://user-images.githubusercontent.com/21121115/46659744-d2259e80-cbb5-11e8-8eb0-a99529e050ed.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 69.0.3497.100

**Comment by plhnk** [comment]
Thanks Victor 😬 we definitely need to style the authcontainer component

**Comment by plhnk** [comment]
"mockup"
![lrdd110-user-dropdown](https://user-images.githubusercontent.com/10226086/47257280-aec5e380-d440-11e8-8f23-ee399781648a.png)
