### ISSUE TITLE
Request to Add Editable LXC Logo to Liferay General Template

### ISSUE THREAD

**Issue by justinwork** [liferay-design/liferay.design#1146]
Apologies if this is the wrong place to file this request. The note said to open a COMMDESIGN ticket but I don't appear to have the appropriate permissions to do so.

My request is to add an editable LXC logo(like the ones for other products) to the -current-liferay-general-template slide deck. I build many internal slide decks for Support and other teams and I use the Logo Sticker Slide often as it has all of our official logos.

Link: https://docs.google.com/presentation/u/0/?ftv=1&tgif=d

Please let me know if any additional information is needed.

**Comment by nhisamoto** [comment]
Hi @justinwork,
I created a [JIRA ticket](https://issues.liferay.com/browse/DESIGN-5030) for you.

**Comment by justinwork** [comment]
Thanks @nhisamoto! I'll close this issue.
