### ISSUE TITLE
Banner h1 text should wrap in hi-res

### ISSUE THREAD

**Issue by cj213x** [liferay-design/liferay.design#138]
Banner in h1 running across the image and over the figcaption on higher resolution screens.

To reproduce, open site on high-res monitor
<img width="1817" alt="screen shot 2018-10-24 at 10 11 36 am" src="https://user-images.githubusercontent.com/26426085/47448582-3a0ee400-d775-11e8-9044-255a08b85c8c.png">

**Comment by plhnk** [comment]
fixed by #381
