### ISSUE TITLE
Logo usage point 7

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#149]
Blueprints logo usage is a bit strange right now in point 7.
Go to Guidelines > Logo

You are explaining a case that is not used anymore. This can be misleading as any other product or site from Liferay could be expressed by using the waffle and the title. Is that what we want?

I noticed that by looking at the left menu where we used to have waffle + Blueprints as the identity for the site.

**Expected behavior**
Either remove point 7. Or use the logo as in the previous version.

**Screenshots**
![image](https://user-images.githubusercontent.com/21121115/47910797-34f81600-de94-11e8-9432-5a79ee826d36.png)

**Desktop (please complete the following information):**
 - Desktop

**Smartphone (please complete the following information):**
 - Chrome latest

**Comment by plhnk** [comment]
Thanks for bringing this up @victorvalle! 

Let me see if I understand — are you saying that we should not allow the use of the icon + a sitename?

We could explain this use-case better, it was meant to help communicate for things like the Partner Portal, the Community site, the Customer Portal, etc — here is the pattern we are using for those:
<img width="1414" alt="screen shot 2018-11-02 at 2 55 46 pm" src="https://user-images.githubusercontent.com/10226086/47942506-6fbb7780-deaf-11e8-87c1-931e9788c23f.png">

here's an example of it live in the new help.liferay:

<img width="1552" alt="screen shot 2018-11-02 at 2 47 13 pm" src="https://user-images.githubusercontent.com/10226086/47942606-c032d500-deaf-11e8-9872-7451386bad7e.png">

here is what we have on Community right now (was a placeholder):
<img width="1552" alt="screen shot 2018-11-02 at 2 48 49 pm" src="https://user-images.githubusercontent.com/10226086/47942633-d80a5900-deaf-11e8-8124-0d3d0b6a4d85.png">

and same for Partner:
<img width="1440" alt="screen shot 2018-11-02 at 2 47 01 pm" src="https://user-images.githubusercontent.com/10226086/47942661-e9536580-deaf-11e8-846f-d432bf039fb8.png">

So eventually we'll have them all be more consistent using this pattern defined here.

Does this context help? How can we make it clearer?

**Comment by victorvalle** [comment]
@plhnk these examples in positive and negative are better. The idea is to show examples that we are doing well so people find them as a source of trust in case they compare.
I see that we are still on the way of adapting many of our sites to our Blueprints. I hope they align little by little =)

**Comment by plhnk** [comment]
(should have been closed years ago)
