### ISSUE TITLE
Emojis break markdown links

### ISSUE THREAD

**Issue by alexandervalencia** [liferay-design/liferay.design#150]
The readme.md links that start with emojis do not correctly jump me down to the anchor point on the page.

e.g. I click on "💁 What do all these files do?" and my url changes to https://github.com/liferay-design/liferay.design#💁-what-do-all-these-files-do but I am not redirected to that section on the page.

**Comment by plhnk** [comment]
nice — thanks for reporting Alex! that's why nobody has been reading the documentation.... 😂

**Comment by plhnk** [comment]
thanks again for reporting @alexandervalencia — finally fixed by [263](https://github.com/liferay-design/liferay.design/pull/263)
