### ISSUE TITLE
Dead link for logo guidelines

### ISSUE THREAD

**Issue by JoshuaStClair** [liferay-design/liferay.design#167]
Navigate to: https://liferay.design/blueprints/resources/logo-files

The link for [logo guidelines](https://liferay.design/docs/guidelines/logo-usage.html) gives a 404 error.

**Comment by plhnk** [comment]
thanks for reporting Josh! 

somebody forgot to do a find/replace for the old url paths.... _(it was me)_

**Comment by plhnk** [comment]
[fixed](https://github.com/liferay-design/liferay.design/pull/169)
