### ISSUE TITLE
Source Team Headshots

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#2]
Ask Abel, Naoki, or Paul for the link to the internal repo of employee photos — there should be headshots for everyone.

There is a folder of test headshots in a new, cool style that needs to be edited.

Then all headshots need to be cropped in a consistent way and saved for web.

**Comment by naoki-evan-hisamoto** [comment]
Maybe PJ and I can work on this!

**Comment by plhnk** [comment]
yeah that'd be awesome!!
