### ISSUE TITLE
Update Liferay Commerce Screenshots

### ISSUE THREAD

**Issue by christinereyes** [liferay-design/liferay.design#241]
Liferay Commerce has a new accelerator design for 1.1. Please update the screenshots at https://liferay.design/blueprints/resources/product-screens/ with the ones we use on liferay.com.

Anything referring to Beryl should be retired.

**Comment by plhnk** [comment]
more details [here](https://github.com/liferay-design/liferay.design/issues/250)

**Comment by plhnk** [comment]
Thanks @abelhancock !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
