### ISSUE TITLE
Add a <title> element to homepage

### ISSUE THREAD

**Issue by jamesjlyons** [liferay-design/liferay.design#266]
The title gives screen reader users an overview of the page, and search engine users rely on it heavily to determine if a page is relevant to their search.

[More detailed information about title elements](https://developers.google.com/web/tools/lighthouse/audits/title)

**Comment by plhnk** [comment]
- Added a default <title> to the main html template
- Added a <title> for the 2018 annual report

TODO: Add dynamic <titles> — use Helmet?

**Comment by plhnk** [comment]
fixed in #533
