### ISSUE TITLE
Add discernible text to footer links

### ISSUE THREAD

**Issue by jamesjlyons** [liferay-design/liferay.design#269]
Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users.

[More info on link text](https://dequeuniversity.com/rules/axe/3.1/link-name)

**Comment by plhnk** [comment]
to clarify — the icons in the footer don't have an `aria-label` specified, so screen-readers can't interpret them

**Comment by plhnk** [comment]
[fixed](0042c59f679d9d34c35594148788a3028cf3bbf2)
