### ISSUE TITLE
Replace WeDeploy Auth

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#280]
**Is your feature request related to a problem? Please describe.**
WeDeploy Auth is going away on April 22 — we need a solution in place before then.

**Folders / Components Affected**

- **utils/index** is where Auth is imported
- **templates/PrivatePage** is where most of the Auth logic lives
- **molecules/AuthContainer and LogoutContainer** might not be affected, but those are the login/logout components

**Comment by plhnk** [comment]
@protoEvangelion did the bulk of the work on [315](https://github.com/liferay-design/liferay.design/pull/315)! (thanks R2!)

remaining things to be fixed before production sync:
1. sign-in button
what it should look like:
<img width="1314" alt="Screen Shot 2019-04-22 at 2 13 57 PM" src="https://user-images.githubusercontent.com/10226086/56531496-008f1980-6509-11e9-9189-673b8c45d925.png">

what it currently looks like:
<img width="1314" alt="Screen Shot 2019-04-22 at 2 14 02 PM" src="https://user-images.githubusercontent.com/10226086/56531511-071d9100-6509-11e9-95b3-7f3a4a2d651a.png">

2. PrivatePage message
what should happen when you try to access a page when you're not logged in:
<img width="962" alt="Screen Shot 2019-04-22 at 2 13 38 PM" src="https://user-images.githubusercontent.com/10226086/56531568-21576f00-6509-11e9-8e09-c54c08d306a6.png">

what is currently happening:
<img width="1382" alt="Screen Shot 2019-04-22 at 2 16 52 PM" src="https://user-images.githubusercontent.com/10226086/56531688-4cda5980-6509-11e9-958c-8750042abf79.png">

3. @abelhancock and @protoEvangelion discuss popup vs. dedicated page for the signin? An immediate con I noticed for the popup, is what if people have a blocker? I think this might be the reason why I wasn't able to solve #2 as quickly...

Thanks all!!!

**Comment by protoEvangelion** [comment]
Swap from wedeploy to firebase auth is here: https://github.com/liferay-design/liferay.design/pull/315
Abel fixed usability issues here: https://github.com/liferay-design/liferay.design/pull/316
I cleaned up a bunch of stuff and included the sign in button styles here: https://github.com/liferay-design/liferay.design/pull/317

**Comment by protoEvangelion** [comment]
In terms of pop up that is what we wanted initially but we had problems with wedeploy right?

Main benefit of popup is speed. We don't have to reload the app.

If they have popups blocked it should show up in their popup blocker. 

It's a tradeoff.

Question is which benefit would you prefer?

**Comment by abelhancock** [comment]
From my understanding, a popup will almost never be blocked when directly triggered by a click (counted as a [trusted event](https://www.w3.org/TR/DOM-Level-3-Events/#trusted-events)). This is a little over my head but after trying to block pop ups from liferay.design the button still worked.
![image](https://user-images.githubusercontent.com/31840274/56544461-68edf300-6529-11e9-92b4-8605662f099c.png)

**Comment by plhnk** [comment]
Thanks for the comments and work @protoEvangelion and @abelhancock! Great work — I wasn't necessarily advocating for or against the popup route, just wanted to hear your thoughts. @abelhancock interesting point, I never knew that
