### ISSUE TITLE
Add "draft" to frontmatter for Lexicon pages

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#309]
Lexicon site has pages that have a "hidden" property so they are not shown in the sidebar.

We would like the sidebar component to be able to take that property and act to not show "hidden: yes" pages.

**Comment by plhnk** [comment]
Can you clarify the use-case? 

To confirm: You want pages to appear inside the folders (i.e. foundations / accessibility) but _not_ show up in the navigation?

**Comment by victorvalle** [comment]
Exactly that is my need. I’ve been trying with node.hidden at sidebar component but without much success

**Comment by plhnk** [comment]
Can you elaborate on the value of this? What are some use-cases where we need a page available within the structure, but unavailable in the traditional navigation? (trying to better understand the requirements, maybe we can discover an alternative)

**Comment by victorvalle** [comment]
So, in the past I used to have a hidden property for the pages to hide them while I'm still working on them but I don't want to make them public yet. I guess this could be solved in other ways.

- Removing current ones I don't want to show now and recover them from git when they are ready.
- Merging the pages only when they are ready to be published.

For sure if we get to solve this issue I don't want hidden pages to be accessed by url.

It is not a big deal, we could close this issue if it is a bit nightmare.

**Comment by plhnk** [comment]
Ahhhh okay — that makes sense! What if we had a "draft" mode? The pages won't be built (indexable, or even accessible by a url) — but they'll be in the markdown folder, and during development you'll be able to see them. 

How does that sound?

**Comment by plhnk** [comment]
Note — I misspoke — the solution I cobbled together still allows the pages to be built (i.e. they will be accessible if you have the url) but they won't show up in the sidebar.

Let me know if this is amenable, otherwise I am closing this issue.
