### ISSUE TITLE
Remove auto-collapsing behavior of the menu

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#327]
**Description**
The master/detail interaction of the accordion menu triggers auto-collapse.

**Steps to Reproduce**
1. Go to 'Sidepanel'.
2. Click on 'Core Components' item.
3. Click on 'Alerts' item.
4. See how the 'Core Components' item collapses.

![auto-collapse](https://user-images.githubusercontent.com/21216422/56758180-4ca2be00-6796-11e9-903b-c9e16f4d54fd.gif)

**Expected behavior**
'Core Components' item should be expanded

**Desktop**
 - OS: MacOS Mojave 10.14.4
 - Browser: Chrome 74

**Comments**
We should try to respect the actions made by users. If he/she opens something, we should not close it unless we have a good reason to do it. Being this a documentation site, a user that wants to browse and explore its content, this issue can be significantly annoying.

**Comment by drakonux** [comment]
I've noticed in some cases the problem is related with the first letter of the naming within src > markdown > lexicon > folders (e.g. core components, examples, etc.) 

<img width="357" alt="Upper vs lower" src="https://user-images.githubusercontent.com/21216422/56760155-e40a1000-679a-11e9-982d-03cc5e32f2fd.png">

**Comment by plhnk** [comment]
thanks for reporting @drakonux!

**Comment by plhnk** [comment]
looks like this is fixed by 6739a66 — also a duplicate of #311

**Comment by drakonux** [comment]
Sorry Paul. I still reproduce it!!! Could you review it please??? cc\ @eduardoallegrini

**Comment by plhnk** [comment]
@drakonux I checked your example, and clicked through all of the top-level items in the sidebar — and a few of the sub-sub items and could not reproduce.

What I did see was if I had navigated to `Core Components > Charts > Colors` _then_ clicked navigated to `Core Components > Cards > Cards Variations` _then_ the `Charts` toggle would collapse...but I think this could be a desired behavior as the user has navigated away from Charts.

Please share where you're reproducing the issue.

Thanks!

**Comment by drakonux** [comment]
Well. That's the key. If it's a desired behavior. It's all said. 

![Accordion-Issue](https://user-images.githubusercontent.com/21216422/57703486-78f87e80-7660-11e9-8fef-103b943f11eb.gif)

In my opinion, the current behavior can make sense as you said. However, I have several doubts if the closing movement doesn't create confusion. 
![issues-movement](https://user-images.githubusercontent.com/21216422/57703942-50bd4f80-7661-11e9-8f6b-77804f555f94.gif)

PS. Notice where is the breadcrumb item when I pressed it for the first time.

**Comment by plhnk** [comment]
So we've fixed it 50% of the way? 😬 

I will leave this issue open so we can solve it the rest of the way

**Comment by drakonux** [comment]
\_(ツ)_/¯ It's up to you! 

I think that behavior could work better with smaller items, where the movement is not as aggressive. But maybe I have a bias for non auto-collapsing accordions. We should do a guerrilla test :wink:.

**Comment by drakonux** [comment]
I was thinking on this issue and I think, as you said, for now it's fixed. My bias I think is related with the current taxonomy we have many categories and the consequences are the movement we talked which is something "normal" and findability problems.
