### ISSUE TITLE
Dataset Display and UI Consistency 

### ISSUE THREAD

**Issue by olafk** [liferay-design/liferay.design#329]
Carried over from https://issues.liferay.com/browse/LPS-87822, as I've been pointed to https://liferay.design/lexicon/core-components/dataset-display/, which doesn't contain the requested standards.
Apologies if they're defined elsewhere - I don't know my way around the rather abstract descriptions of Lexicon, just recognize inconsistencies in the concrete product.

This is all in the context of Liferay 7.0 and 7.1

As an example, I'll use the Control Panel / Sites / Sites listing 
![grafik](https://user-images.githubusercontent.com/87909/56806461-465f2100-682c-11e9-87e9-1788df84edd5.png).

* When you create a new Site (+ button), the next form will be the site's Site Settings.
* Site Settings are the second entry down in the "Action/Kebap" menu of the line (screenshot), despite being the default target of "Add Site".
* When clicking on an existing site's name, user ends up at the site's "Pages" configuration.

Similar example:

* User Groups: Adding a user group ends up in the listing of the existing user groups (side effect: This might not be ideal if there are hundreds of user groups - After creating another Usergroup, the admin needs to remember&search for it in order to do anything with it)
* Clicking a Usergroup's name brings us to the "Assign Members", which otherwise would be the fifth entry down in the "Actions/Kebap" menu

In contrast to User Group, different behavior for Roles:

* Adding a new role stays on the same screen, just now with enabled "Define Permissions" and "Assignees" tabs.

**Comment by plhnk** [comment]
hey @olafk — sorry to send you to yet another Jira project 😬 but this repo is for the Lexicon site, from what I can tell, this issue might be better suited as a [LEXI ticket](https://issues.liferay.com/projects/LEXI/) (a 'proposal' perhaps?)

cc @victorvalle

**Comment by olafk** [comment]
Thanks, and sorry, @plhnk 
Filed [LEXI-568](https://issues.liferay.com/browse/LEXI-568)

**Comment by plhnk** [comment]
@olafk no apology necessary! It’s on us to make sure filing issues is clearer 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
