### ISSUE TITLE
Appears to be horizontal overflow on homepage only

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#341]
there's 'horizontal jiggle' on the homepage that shouldn't be there - doesn't seem to be set to 100% the width of the page -- only happened after top banner was introduced so I'm sure that's the cause.

**Comment by plhnk** [comment]
Can you provide more details? (e.g. browser? viewport size?)

A screencast would be great, I'm unable to replicate this issue.

**Comment by ryconn888** [comment]
it occurs on chrome, firefox, and edge - that's all i tested. and pretty much every viewport width except mobile

not a huge deal --- i'll just show you next week

**Comment by plhnk** [comment]
Is this it? [(sorry for the crappy gif)](http://www.giphy.com/gifs/RJJmRgKTWeVrynpG0Y)

**Comment by ryconn888** [comment]
yes

**Comment by plhnk** [comment]
@ryconn888 has this been fixed in the recent updates?

**Comment by ryconn888** [comment]
indeed it has. i will close now
