### ISSUE TITLE
"Get Started" hover issue on Lexicon site

### ISSUE THREAD

**Issue by fapires** [liferay-design/liferay.design#352]
**Describe the bug**
When hovering over the "Get Started" button, there is no indicator to show that is an interactive element (neither point cursor nor hover effect).

**Screenshot**
![get-started-button-hover-issue](https://user-images.githubusercontent.com/8724228/57324344-fca0f100-70dd-11e9-8d4b-0f912f82381c.gif)

**Comment by plhnk** [comment]
_FYI this needs to be fixed at the component level — the `Button` component lives in the `atoms` folder._
