### ISSUE TITLE
Lexicon home page design adjustments

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#382]
Adjust the Lexicon home page to how it looked before moving into gatsby.

**Comment by plhnk** [comment]
what it looks like now: ![screencapture-liferay-design-lexicon-2019-05-13-13_52_13](https://user-images.githubusercontent.com/10226086/57653377-83dee080-7586-11e9-985d-4b6ae8993588.png)

what it looked like before migration: ![screencapture-web-archive-org-web-20190110083439-https-lexicondesign-io-2019-05-13-13_42_38](https://user-images.githubusercontent.com/10226086/57653379-83dee080-7586-11e9-9f59-60a2537f6926.png)

[Archive.org for Jan 10, 2019](https://web.archive.org/web/20190110083439/https://lexicondesign.io/) 

@victorvalle looks like there's a number of things, what do you think about moving this issue to a project and creating subtasks, or something like that?

**Comment by victorvalle** [comment]
I'm ok with the subtasks.

@atjuan is taking a look into this but the css is very different to what he coded in the previous site. So we are still learning how to solve this page css issues :)

**Comment by plhnk** [comment]
okay great! I started a @liferay-design/lexicon team — please add the appropriate people; I also [started a project](https://github.com/liferay-design/liferay.design/projects/5) — if you guys break down the problems and create issues in there it will be easier to tackle!

gracias guapi

**Comment by victorvalle** [comment]
@eduardoallegrini please help :)

**Comment by eduardoallegrini** [comment]
https://github.com/liferay-design/liferay.design/pull/412

**Comment by plhnk** [comment]
thanks to @eduardoallegrini for the updates:
![progress so far](https://user-images.githubusercontent.com/10226086/58506500-5f693380-8144-11e9-81aa-a00e5a55a258.png)
