### ISSUE TITLE
Use Tag Manager

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#395]
I think including Tag manager could have a good potential to check the impact that for example our resources are having:

- For each library
- For each link to prez or prez
- For the assets in blueprints

I don't know if this would help to convert more but at least to track better. Right now we only have information about the navigation with Google Analytics.

**Comment by plhnk** [comment]
https://issues.liferay.com/browse/LWM-1498

**Comment by plhnk** [comment]
using the [gatsby-plugin-google-tagmanager](https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/)

**Comment by plhnk** [comment]
fixed via #397

**Comment by plhnk** [comment]
Note — per the plugin docs —
> Out of the box this plugin will **simply load Google Tag Manager** on the initial page/app load. It’s up to you to fire tags based on changes in your app. To automatically track page changes, in GA for instance, you can configure your tags in GTM to trigger on History Change.

**Comment by victorvalle** [comment]
I wasn't expecting to have it so immediately. I will work out soon on tracing different resources.

Thanks @plhnk !

**Comment by plhnk** [comment]
when @victorvalle says jump, i say 'how high'
