### ISSUE TITLE
Sidebar in Lexicon showing pages from Lexicon-1

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#396]
There is a strange behavior where pages of Lexicon-1 site are being showed in Lexicon site.

**Christian Berndt** described this:

> Can anyone explain the status of https://liferay.design/lexicon and https://liferay.design/lexicon-1?
> I'm currently preparing a Front-End training and I have to admit that I'm confused
> When I start at https://liferay.design/lexicon/get-started I'm suddenly taken to https://liferay.design/lexicon-1/patterns/alerts/
> in https://liferay.design/lexicon/get-started I find overlapping menu entries in the Patterns and the Components entry

**Comment by victorvalle** [comment]
<img width="654" alt="Screen Shot 2019-05-14 at 3 20 01 PM" src="https://user-images.githubusercontent.com/21121115/57701780-fc17d580-765c-11e9-8fc4-c3c1ce4ae5f6.png">

**Comment by victorvalle** [comment]
I think the problem comes in this line:
allMdx(filter: { fields: { slug: { regex: "/lexicon-1/" } } }) {

**Comment by victorvalle** [comment]
@plhnk the only solution I found for this is renaming lexicon markdown folder to lexicon-2 and then making some modifications in different files to adjust texts from "lexicon" to "lexicon-2".

Do you find any other solution that could only affect the slug? maybe a better regex definition that excludes lexicon-1?

**Comment by plhnk** [comment]
if you surround `/lexicon/` with `/(` `)/` that should solve your regex

so finally it will be `/(/lexicon/)/` --> this will only pull the files in the "lexicon" folder

**Comment by victorvalle** [comment]
Thanks @plhnk ! ❤️
