### ISSUE TITLE
Blueprints Products screenshots outdated

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#411]
**Description**
Several screenshots in Blueprints > Resources > Product Screenshots will get outdated really soon.
We should prepare for the change so our users can trust in the shots the find in the site.

**To Reproduce**
1. Go to 'Blueprints > Resources > Product Screenshots

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21121115/58458519-bb728e80-8129-11e9-8283-2af11ec33b79.png)

**Comment by plhnk** [comment]
@abelhancock — I did a brief search in Jira, but could not locate a master ticket, or epic for the release...is there one place where we can get all these assets?

**Comment by abelhancock** [comment]
@plhnk assets aren't attached directly to tickets but they are all in drive. Here is a sheet with links https://docs.google.com/spreadsheets/d/1BhGSn8jk69DieXgBVopI2Mnfi54Gg9LgUSGhZglS0Do

**Comment by sharonchoi** [comment]
@plhnk @victorvalle @abelhancock Here are the product screenshots for DXP 7.2: https://drive.google.com/open?id=1zikF1QSnhgCG6XU4eYZUdyZ5Og_cZBJA

Names should be more or less straightforward, let me know if you need help clarifying!
