### ISSUE TITLE
Add two docs to the templates page

### ISSUE THREAD

**Issue by emilyyoung** [liferay-design/liferay.design#424]
Case study templates:

A4
https://docs.google.com/document/d/1c8tAVddwD5Ju450a-oJwJ2uxHoKQU604KVjvqzdJ4rs/edit?usp=sharing

Letter
https://docs.google.com/document/d/1lR5qb2Rqzwl1gytSsGaK6KqeoedXrKiWEmuAv9dQdRk/edit?usp=sharing

**Comment by victorvalle** [comment]
@emilyyoung I see that we only show the covers for the A4 documents here.
This will be the result for Case Study. Let me know it it is right, please.

<img width="779" alt="Screen Shot 2019-10-22 at 2 56 49 PM" src="https://user-images.githubusercontent.com/21121115/67288114-a9c8c380-f4dc-11e9-8bf5-e7948b78d7e4.png">

**Comment by victorvalle** [comment]
Fix https://github.com/liferay-design/liferay.design/pull/578
