### ISSUE TITLE
There are 7 points in the image, but only 6 in the description

### ISSUE THREAD

**Issue by fapires** [liferay-design/liferay.design#425]
<img width="773" alt="Screen Shot 2019-06-06 at 16 35 01" src="https://user-images.githubusercontent.com/8724228/59061374-bc1dca00-8879-11e9-8d23-9404bd4dd872.png">

**Comment by drakonux** [comment]
Thanks @fapires. Pull request sent here: https://github.com/liferay-design/liferay.design/pull/429

**Comment by victorvalle** [comment]
Merged
