### ISSUE TITLE
Blueprints 7.2 DXP there is image from AC

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#436]
I would say this image shouldn't go inside blueprints 7.2 DXP
![image](https://user-images.githubusercontent.com/21121115/59552059-0d435300-8f37-11e9-943d-eae581d62496.png)

**Comment by victorvalle** [comment]
https://github.com/liferay-design/liferay.design/pull/437

**Comment by plhnk** [comment]
fixed by #437
