### ISSUE TITLE
Attribute to change underline color in side bar and header

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#442]
We need an attribute to change the underline color to meet the theme

![image](https://user-images.githubusercontent.com/21121115/59553016-0d961b00-8f44-11e9-86d9-13776be52408.png)

**Comment by victorvalle** [comment]
I'm working on it but not succeeding yet

**Comment by plhnk** [comment]
can you describe more the desired behavior? where should this underline color come from?

**Comment by plhnk** [comment]
(fixed by #443)
