### ISSUE TITLE
Netlify CMS `slug` bug

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#448]
On the `netlify-cms` branch — when running it locally, the `/articles` page doesn't render because:
![image](https://user-images.githubusercontent.com/10226086/60153407-fdc6d400-9798-11e9-8633-5266380a036a.png)

I suspect this is because in `gatsby-node.js` we're creating a `slug` field so that the pages have nice urls.

**Comment by plhnk** [comment]
what I don't understand is that the `slug` field shows up in graphiql:
![image](https://user-images.githubusercontent.com/10226086/60193697-fb8e6500-97ec-11e9-8ab2-8d8f56ee03d0.png)

any ideas @protoEvangelion ?

**Comment by protoEvangelion** [comment]
My guess is that at least one of the slugs is not getting defined. Can you do `console.log(slug, title)` and look for the one that is not defined?

**Comment by plhnk** [comment]
all of them are there :/ 

![image](https://user-images.githubusercontent.com/10226086/60214635-b84aeb00-981a-11e9-9f37-05c99507cd7f.png)

**Comment by plhnk** [comment]
Okay — not sure how I did it, but its working now!

New problem: [Netlify CMS doesn't support nested folders](https://github.com/netlify/netlify-cms/issues/513) :/ have to consider an alternative CMS
