### ISSUE TITLE
Same image is used for "Do" and "Don't" on Table component page

### ISSUE THREAD

**Issue by dejuknow** [liferay-design/liferay.design#458]
**Describe the bug**
The same image is used for _Do_ and _Don't_ on the Lexicon Table component [page](https://liferay.design/lexicon/core-components/table/table/). See screenshot below.

<img width="1514" alt="_screenshot 2019-07-09 at 12 42 30 PM" src="https://user-images.githubusercontent.com/599111/60918170-80df3400-a247-11e9-9b11-1022337d705b.png">

**Comment by victorvalle** [comment]
Thanks @dejuknow ! :)
Fixed https://github.com/liferay-design/liferay.design/pull/459
