### ISSUE TITLE
Lexicon Contribution link is broken

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#492]
**Description**
Lexicon Contribution link is broken.

**Steps to Reproduce**
1. Go to 'https://liferay.design/lexicon/'
2. Scroll down to 'Want to contribute' section
3. Click on 'Github repo' link

**Expected behavior**
Navigate to https://github.com/liferay-design/liferay.design/issues

**Current behavior**
404 page

**Screenshots**
![image](https://user-images.githubusercontent.com/21216422/62349870-45abea00-b501-11e9-9fab-cf230e7fee03.png)

**Additional context**
Tony Lim from the Tokyo office reported it via Slack. Thanks Tony!

**Comment by plhnk** [comment]
would you want to narrow the issues down to [ones tagged w/Lexicon](https://github.com/liferay-design/liferay.design/labels/lexicon)?
