### ISSUE TITLE
Lexicon side panel title breaks into two lines

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#500]
**Description**
The main title of the site: "Lexicon.Design / Lexicon" breaks into two lines when the side panel content overflows.

**To Reproduce**
1. Go to 'https://liferay.design/lexicon/get-started'
2. Click on 'Core Components'
3. See error

**Expected behavior**
The title remains in a line without a line break. 

**Screenshots**
![Microsoft Edge - Line break](https://user-images.githubusercontent.com/21216422/62950670-ca8fe100-bde8-11e9-8637-45e8a2222965.gif) 
_Microsoft Edge for Windows_ 

![image](https://user-images.githubusercontent.com/21216422/62950227-efd01f80-bde7-11e9-9140-e922edd5602d.png)
 _Chrome for MacOS_

**Desktop**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 42.17

**Comment by plhnk** [comment]
temp fix in place — #322 should solve this
