### ISSUE TITLE
Lexicon old URL redirects

### ISSUE THREAD

**Issue by abelhancock** [liferay-design/liferay.design#510]
**Describe the bug**
Lexicon has outdated urls out there on the interwebs with containing `/docs` that lead to blank pages.

**To Reproduce**
1. Try to visit https://liferay.design/lexicon/docs/core-components/charts/chart-color-palette.html
2. See a blank page

**Expected behavior**
The above link (and any link with `/docs`) should redirect to https://liferay.design/lexicon/core-components/charts/chart-color-palette.html (or the equivalent)

**Comment by victorvalle** [comment]
Thanks @abelhancock ! Fixed on https://github.com/liferay-design/liferay.design/pull/511

**Comment by victorvalle** [comment]
Don’t know where to do that :(
