### ISSUE TITLE
sexyShadow hover transition choppy in Firefox

### ISSUE THREAD

**Issue by jamesjlyons** [liferay-design/liferay.design#535]
Regarding [this commit](https://github.com/liferay-design/liferay.design/commit/2de1bd4071c82dc39994e2ec4ba38748022467db). The `filter: blur(3rem)` property on the underlying image is causing the hover animation to be slow on the latest Firefox 69.0 and Firefox Dev 70.0b6. It might be related to [this Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=925025) around CSS Blur performance.

![Kapture 2019-09-13 at 10 35 09](https://user-images.githubusercontent.com/4167843/64882750-9dfefd00-d612-11e9-9ea5-c83878d5da98.gif)

**Comment by plhnk** [comment]
thx for reporting! ideas to solve?

**Comment by plhnk** [comment]
:crickets: — you can [target -moz browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions#font-family)
