### ISSUE TITLE
Closing action not available for the "join us" banner 

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#543]
**Describe the bug**
I can't close the "join us" banner. 

**Steps to Reproduce**
1. Go to 'https://liferay.design/'

**Screenshots**
![image](https://user-images.githubusercontent.com/21216422/65015389-b37d6b00-d921-11e9-81ee-0fd134e8f773.png)

**Desktop**
 - OS: macOS Mojave 10.14.6 
 - Browser: Chrome  
 - Version: 76.0.3809.132 

**Reasoning**
It's ok to steal space to the page but at least let users recover that space.

**Comment by plhnk** [comment]
👍  maybe we can introduce a dark pattern where the "close" button takes them to `/careers`? 

_cc @susanavr_

**Comment by susanavr** [comment]
Please don't do it, Paul!!! 
Ok, let's get serious... we want to enhance them, but not make them hate us because of a bad user experience. So I suggest not to use dark patterns. So sorry I know that you wanted to hear a different thing... :zipper_mouth_face:

**Comment by susanavr** [comment]
And looking into the same page I have just realized that "Liferay's global team of" does not feel very contrasted. I have doubts that the sentence is accesible!

**Comment by plhnk** [comment]
@susanavr it was only a joke about the dark pattern... :D 

yes you're right...it does not pass AA — but it's somewhat by design? But would love to see a proposal for an alternative that passes contrast accessibility while also maintaining the integrity of the idea behind it "we are designers"
