### ISSUE TITLE
"Join us" banner doesn't extend correctly on large screens 

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#544]
**Describe the bug**
There is a missing white space on the right of the "join us" banner using large screens.  

**Steps to Reproduce**
1. Go to 'https://liferay.design/'

**Expected behavior**
The join us banner should fill all the horizontal space 

**Screenshots**
<img width="2558" alt="Screenshot 2019-09-17 at 07 59 52" src="https://user-images.githubusercontent.com/21216422/65016216-fc362380-d923-11e9-9e97-3a63b4772ee5.png">

**Desktop**
 - OS: macOS Mojave 10.14.6 
 - Browser: Chrome  
 - Version: 76.0.3809.132
- Resolution: 2560x1440 

**Additional context**
May be this is intended by design 😃. Then, is it working to its purpose?

**Comment by plhnk** [comment]
see #386 :)

**Comment by drakonux** [comment]
So is it working???
