### ISSUE TITLE
Copy in Modal Page has a typo

### ISSUE THREAD

**Issue by jonmwood** [liferay-design/liferay.design#547]
**Describe the bug**
From the Modal page on the Lexicon site, the copy in the Footer section should be ‘align them to the right’ instead of 'left'.

**To Reproduce**
1. Go to https://liferay.design/lexicon/core-components/modals
2. Go to the Usage paragraph 4th bullet
3. Text shows When a modal has a footer, place the actions inside and align them to the **left.** Follow this order for your actions: Primary button (only one), secondary button, and button link.

**Expected behavior**
Text should be: When a modal has a footer, place the actions inside and align them to the **right.** Follow this order for your actions: Primary button (only one), secondary button, and button link.

**Comment by victorvalle** [comment]
@drakonux maybe this is an opportunity to review if there is some description missing related to extra buttons on the left side of the footer.

**Comment by drakonux** [comment]
Thanks guys!! you are right @jonmwood . I will take a look as soon as I can 🙏Victor.

**Comment by victorvalle** [comment]
Fixed on https://github.com/liferay-design/liferay.design/pull/577
Thanks @jonmwood ! Sorry for the delay.
