### ISSUE TITLE
Articles title and images are misplaced on mobile

### ISSUE THREAD

**Issue by p2kmgcl** [liferay-design/liferay.design#550]
**Describe the bug**
Post title and cover are misplaced on Firefox on Android.
Images bigger than the page width are cropped too.

**To Reproduce**
1. Go to https://liferay.design/articles/best-practices/usability-testing-zero-users-give-zero-insights/
2. See error

![Screenshot_20190925-175434](https://user-images.githubusercontent.com/800645/65618994-a0246c80-dfbf-11e9-8b8e-669fcb8ec79b.jpg)

**Comment by plhnk** [comment]
thanks for reporting @p2kmgcl !

**Comment by plhnk** [comment]
fix incoming
