### ISSUE TITLE
no active state for primary navigation

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#555]
Rather than having the Logo have a '/' followed by what page you're on we should just have an active state for the primary nav - (example: active state could be the maintained hover state - white text with underline)

**Comment by plhnk** [comment]
Thanks for requesting — we used to have this way back in v1. If anyone picks this up, here is one way to go about doing it:

1. list of options
1. apply a 'selected' class to the entry's selected
1. style appropriately

[Here's how it was done before](https://github.com/liferay-design/liferay.design/commit/df5f14036ed2d62bfc6065dfaeeff6d1b5a59456#diff-3c0089f1ef479b158ea6dd3226b66567) —  issues I could see w/doing it that same exact way again would be abstracting [the options and navKeys](https://github.com/liferay-design/liferay.design/commit/df5f14036ed2d62bfc6065dfaeeff6d1b5a59456#diff-cc6b845ad8d8ee8aba0223fcc1a12475) out so you don't have to keep repeating them for every instance of the nav.
