### ISSUE TITLE
Quotes break for articles in mobile

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#559]
While reading Chris last article post I noticed that quotes are hard to consume as they are wider than the viewport width

![E0B53C04-EAF9-48B4-81DF-C484F88836DF](https://user-images.githubusercontent.com/21121115/66181284-7d095500-e670-11e9-927d-c6a05f4d91b4.png)
![584C5A9E-D74A-4AA0-9D5F-BFCAD03E2CC9](https://user-images.githubusercontent.com/21121115/66181285-7da1eb80-e670-11e9-9012-659eaf45c5d8.png)

**Comment by plhnk** [comment]
fixed in f9a9dc0
