### ISSUE TITLE
Have hyperlinks open on a new page

### ISSUE THREAD

**Issue by emilyyoung** [liferay-design/liferay.design#570]
Currently links open on same page, making user click back to get back to the article and starting over from top of page

**Comment by plhnk** [comment]
Very do-able! 

_Notes for anyone who'd like to pick this up:_

We have a `<Link>` component (src/components/atoms) — it leverages Gatsby's Link component for nice internal linking, but also handles external links.

I believe we might be able to add a `target='_new'` (is `_blank` better?? idk) to the external link part of this component, seems safe to assume any external link should open in a new window?

**Comment by plhnk** [comment]
Update — [use _blank](https://chilts.org/target-blank-or-new/) and specify a [rel](https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f) to prevent security issues.
