### ISSUE TITLE
Event and Team page titles incorrect

### ISSUE THREAD

**Issue by abelhancock** [liferay-design/liferay.design#589]
Event and Team pages are dynamically pulling page titles from the page content.

1. Go to /events or /team
2. Click on an event or team member
3. See the page title pulled from the body content, not the h1

**Expected behavior**
Page titles are the same as h1

**Screenshots**
<img width="800" alt="screen shot" src="https://user-images.githubusercontent.com/31840274/67986238-d02ae500-fbe7-11e9-8dcd-f7b9de7269c9.png">

**Additional info**
Page titles also do not update when navigating away from one of these pages.

**Comment by plhnk** [comment]
thanks for reporting — note for anyone who wants to fix this, check out the `<SEO>` component that's on these page templates
