### ISSUE TITLE
Visual representation for avoid option

### ISSUE THREAD

**Issue by laugardie** [liferay-design/liferay.design#609]
**Request**
In the Lexicon site, there are two visual representation to show dos and don'ts. Working on [LEXI-716](https://issues.liferay.com/browse/LEXI-716) to create a new pattern, we need a way of representing an option that should be avoided only in certain cases.
<img width="505" alt="Screenshot 2019-12-05 at 11 11 02" src="https://user-images.githubusercontent.com/56547676/70225762-ef211780-174f-11ea-9db1-a11c5e916532.png">

**Describe the solution you'd like**
I would like to have a way to represent avoid options. I suggest using these two colors:
**Accent 2:** #E06E31 (_typography_)
**Orange:** #FFB46E (_line_)

<img width="252" alt="Screenshot 2019-12-05 at 11 14 19" src="https://user-images.githubusercontent.com/56547676/70226034-68206f00-1750-11ea-82d6-5b26e795101c.png">

**Comment by plhnk** [comment]
Thanks @laugardie! Are you working on this?

**Comment by laugardie** [comment]
Yes, I am working on it. I have already made the changes but I am having this problem after trying to do a pull request. Do you know how to solve it?
<img width="482" alt="Screenshot 2019-12-10 at 12 00 47" src="https://user-images.githubusercontent.com/56547676/70551262-78cd4c80-1b77-11ea-9b6b-d4ffa193852c.png">

**Comment by plhnk** [comment]
what happens when you try that command?

**Comment by laugardie** [comment]
It tells me the same instruction over and over again.

**Comment by plhnk** [comment]
fixed by #612 — thanks @laugardie !
