### ISSUE TITLE
Captcha issue to run the site

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#614]
There is something that prevents running the site related to a captcha config file.

**Comment by plhnk** [comment]
sorry victor — this is because you need a local `.env.development` w/our recaptcha keys, not sure the best way to share this w/everyone....but will figure it out!

**Comment by victorvalle** [comment]
Where do I have to put this file? I have to do it again :(

**Comment by plhnk** [comment]
for now — a workaround for this is in our Slack, I'm still working on a better solution. Until then, [please reference this thread](https://liferay.slack.com/archives/CLARSSP9D/p1577286071000300?thread_ts=1577207286.001400&cid=CLARSSP9D).
