### ISSUE TITLE
2019 Annual Report TODOs

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#623]
**This issue is to create a running list of things we'd like to do!** 

Add comments, checklists, requests, etc.

**Comment by plhnk** [comment]
- [ ] max-width on page for extra-large screens
- [ ] refine top-banner area
- [ ] make text in nav items always show 
- [ ] add fade-in at the top and bottom of the timeline
- [ ] add row and fade-out best-practices
- [ ] YAML-fy the events
- [ ] YAML-fy the designers

**Comment by plhnk** [comment]
- [ ] update SEO image @ryconn888

**Comment by plhnk** [comment]
- [ ] add a link back to the main design site

**Comment by ryconn888** [comment]
- [ ] 'Design Report' text should fade in once the 2019 starts animating. 
- [ ] 'Design' should be 60% FFF and 'Report' should be 100% FFF
- [ ] Double the left-padding in Department Organization, that text is too close to the edge
- [ ] Need new image asset for Path Tool that doesnt' use a real designer's name, also fix text padding on image asset if there's time...
- [ ]

**Comment by plhnk** [comment]
- [ ] make nav friendly for smaller desktops
- [ ] content for GS section
- [ ] content for ops section
- [ ] circular avatars for Projects people
- [ ] avatar for analytics cloud
- [ ] note from director at the end
- [ ] clean up dribbble content
- [ ] add link out to our dribbble somewhere
- [ ] tweak DBP section so final row is cropped on the bottom
- [ ] content in Grow & get better section

**Comment by plhnk** [comment]
- [ ] add negative margin to left-aligned headings so they line up better w/rest of the text

**Comment by abelhancock** [comment]
- [ ] Hide scroll arrow after scrolling from top

**Comment by victorvalle** [comment]
Juan H message and signature
- [ ] The message should be narrower, 600px max.
- [ ] The signature should be small
- [ ] The headshot should be rounded as others in the page
- [ ] The headshot, signature, and name should go together below the message

**Comment by plhnk** [comment]
@victorvalle the weird behavior is a parallax effect from @abelhancock ;)

**Comment by plhnk** [comment]
- [ ] fix fill on desicon

**Comment by plhnk** [comment]
- [ ] solve paragraph issue (multiline strings in YAML file get rendered in a single tag, instead of a tag per line) --> https://michaelwatts.co/blog/2019-07-31-adding-netlify-cms-to-gatsby-part-1/

**Comment by plhnk** [comment]
- [ ] update sideTab to promote report

**Comment by davidhskim** [comment]
- [ ] Highlight the word "research" instead of "design"

<img width="1181" alt="Screen Shot 2019-12-27 at 9 36 57 AM" src="https://user-images.githubusercontent.com/43387132/71526601-84658680-288c-11ea-9671-c34f41a4bd66.png">

**Comment by plhnk** [comment]
dev'd per the mockup (more or less) — @ryconn888 thoughts?
<img width="1180" alt="Screen Shot 2019-12-27 at 9 45 22 AM" src="https://user-images.githubusercontent.com/10226086/71526888-b7f4e080-288d-11ea-95e5-440da648ac6b.png">
