### ISSUE TITLE
https://liferay.design/lexicon seems broken on Chrome / Chromium 

### ISSUE THREAD

**Issue by chrberndt** [liferay-design/liferay.design#660]
**Describe the bug**

https://liferay.design/lexicon seems broken on Chrome / Chromium 

Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.11 (64-bit)

There is no scrollbar visible and you can't scroll the page even with up and down arrows.

**To Reproduce**

1. Go to 'https://liferay.design/lexicon'
2. Click on 'https://liferay.design/lexicon'
3. No scrollbar
4. Can't scroll with arrows

The error console displays: 

The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Expected behavior**

The page is expected to show a scrollbar and be scrollable

**Screenshots**

**Desktop (please complete the following information):**

Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.11 (64-bit)

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone X]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by plhnk** [comment]
Hey @chrberndt — thanks again for filing this issue!

I'm having some trouble reproducing it, maybe you can point me in the right direction — here's what I've tried so far:
1. [how can I run an older version of chrome](https://www.reddit.com/r/chrome/comments/a41gkh/is_there_a_way_to_use_old_versions_of_chrome/)
1. [older versions of chrome for various platforms](https://www.slimjet.com/chrome/google-chrome-old-version.php) — (they don't have version 73 for mac — it goes from v71 to 75 — I tried 71 but it seems to be working)

Do you know of any way to run different versions of chrome?

Alternatively, if you could troubleshoot further, perhaps by inspecting the page you could narrow down if there's a styling class causing this or maybe even a console error?

**Comment by chrberndt** [comment]
Hi @plhnk - as far as I can see the issue is not limited to old versions of chromium. Unfortunately I encounter the same behaviour (no scrollbar, no scrolling with arrows) with Chromium Version 80.0.3987.100 (Official Build) snap (64-bit) on Ubuntu 18.04.3 LTS as well. 

Maybe a Chromium and or Linux issue? You might want to check https://liferay.design/lexicon/ with Chrome / Chromium 80 which is available for mac as well. See: https://www.chromium.org/getting-involved/download-chromium

**Comment by plhnk** [comment]
thanks @chrberndt — I believe this may be isolated to Linux? 

Behaves as expected:
![image](https://user-images.githubusercontent.com/10226086/76364089-9d090880-62e1-11ea-80b6-f601089f4360.png)
_(Chromium v82.0.4 on macOS 10.14.6)_

Perhaps we can schedule a time to screenshare? I'm currently out of office, but will be available on Monday, March 16. Ping me in Slack and we can coordinate from there.

**Comment by drakonux** [comment]
Hi guys,

Just to add more information, Jacob Cerda reported these tickets yesterday using Ubuntu 18.04.4:

- https://issues.liferay.com/browse/LEXI-895
- https://issues.liferay.com/browse/LEXI-896

I also run my own tests:

OS
**Windows 10 Pro (v1903)**

BROWSERS

**Edge v81.0.416.64 (64 bits)**
![edge](https://user-images.githubusercontent.com/21216422/80463989-680c5000-8939-11ea-8522-5f8f581c20e2.gif)

**Chrome v81.0.4044.129 (64 bits)**
![chrome](https://user-images.githubusercontent.com/21216422/80464002-6e023100-8939-11ea-88db-1cf933b114d7.gif)

**Comment by plhnk** [comment]
thanks for linking @drakonux — I'll look into it...

In other news, what is going on w/the type in your screenshots??

**Comment by drakonux** [comment]
Just Windows I think :), but let's talk in #726 if you want...

**Comment by drakonux** [comment]
Hi, @plhnk I still don't see the scrollbars using Edge and Chrome. And using Firefox I only can see the scrollbar in the side panel of the Lexicon Site. 

**Firefox**
![firefox-scrollbar](https://user-images.githubusercontent.com/21216422/104324876-46172580-54e8-11eb-8861-39ce83279d08.gif)

Maybe you should reopen this ticket or do you need a new one?

**Comment by plhnk** [comment]
Hm — yes @drakonux can you make a new one? I tried reproducing a little, but couldn't. Since this isn't related to this older issue, better to start a new one.
