### ISSUE TITLE
Logos do's and don'ts

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#663]
I would change logos page, usage section to something more visual rather than a plain list. Maybe this is something that you already have in mind.
This is how we do it in Lexicon Site:
![image](https://user-images.githubusercontent.com/21121115/42266586-23e4477a-7f77-11e8-8b90-b415456c34f2.png)

**Comment by plhnk** [comment]
fixed :) thanks @victorvalle 

<img width="1792" alt="Screen Shot 2020-02-05 at 9 21 33 AM" src="https://user-images.githubusercontent.com/10226086/73865974-ece34400-47f8-11ea-9c7a-474f7679e3d3.png">
