### ISSUE TITLE
Safari on OS-X: 404s

### ISSUE THREAD

**Issue by dnebing** [liferay-design/liferay.design#665]
Main page shows a number of 404s.
![liferay404s](https://user-images.githubusercontent.com/15354921/42350529-f3c2a588-807e-11e8-80a8-56b643d7acb7.png)

**Comment by plhnk** [comment]
fixed :) 

<img width="1182" alt="Screen Shot 2020-02-05 at 9 15 01 AM" src="https://user-images.githubusercontent.com/10226086/73865400-09cb4780-47f8-11ea-875c-15967e79611e.png">
