### ISSUE TITLE
Sidebar not working well

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#668]
The new mechanism doesn't work well for pages inside Lexicon/Satellites

The menu doesn't remain open when it should.

**Comment by plhnk** [comment]
I'm looking into this...also chatting w/Bryce to learn how Clayui.com maintains the state of their sidebar...

**Comment by victorvalle** [comment]
Duplicates https://github.com/liferay-design/liferay.design/issues/814
