### ISSUE TITLE
Liferay.Design isn't visible in the Lexicon footer

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#671]
![image](https://user-images.githubusercontent.com/10226086/74097123-69a64480-4abd-11ea-9928-d5fba62d6b4b.png)

the text is there, there's just some css overriding it: 
![image](https://user-images.githubusercontent.com/10226086/74097160-a83bff00-4abd-11ea-8d44-90a074d55423.png)

**Comment by plhnk** [comment]
@drakonux I basically scoped the `documentation` styles to the docs template (so they don't affect the Lexicon homepage) — [here's a before/after](https://www.figma.com/file/OstWRVg7WiuwFacnZMKJhW/671?node-id=1%3A6) — there are a few other implications...please comment in Figma if they should be preserved :) 

cc @victorvalle @atjuan

**Comment by plhnk** [comment]
_(reopening until @drakonux approves 🐲)_

**Comment by victorvalle** [comment]
😄 
I see it working, but lets wait for @drakonux :)

**Comment by drakonux** [comment]
I have to say, that the new one looks ok 😅 thanks, guys.

**Comment by plhnk** [comment]
thanks all — closing it out now!
