### ISSUE TITLE
Fix Broken Links

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#674]
A number of the 'View in Clay' links I've come across have been broken...but the pattern looks predictable — as far as I can tell, we need to add `v2.` as a prefix, and they've changed from `_` to `-` in their urls.

See [Bar Chart's](https://liferay.design/lexicon/core-components/charts/chart-stacked-bar/) for example.

(Updated to include broken links across the site — full table below, checklist to track in the comments)

||||||
|--- |--- |--- |--- |--- |
|#|link|Link Text|Page where found|Server response|
|1|https://www.liferay.com/404|404|https://liferay.design/articles/2019/increasing-our-ability-to-convert-prospects/|404|
|2|https://assets-liferaydotdesign.wedeploy.io|web assets repo|https://liferay.design/articles/2019/netlify-vs-zeit-vs-github-pages/|bad host|
|3|https://wedeploy.com/blog/discontinuing-wedeploy/|they were shuttering the service|https://liferay.design/articles/2019/netlify-vs-zeit-vs-github-pages/|404|
|4|https://help.figma.com/category/87-prototyping|documentation|https://liferay.design/articles/2019/how-to-use-any-clicker-with-figma-presentations/|404|
|5|htttp://www.lexicondesign.io|Design Systems|https://liferay.design/articles/2018/year-one-retrospective-cj/|bad url|
|6|https://www.radicalcandor.com/blog/tag/tip/|finer points of strong culture-building|https://liferay.design/articles/2018/new-team-assemble/|404|
|7|https://seths.blog/2018/04/missing-from-your-job-office/|Seth Godin’s list|https://liferay.design/careers/latam/product-designer/|404|
|8|http://www.terremoto.net/pv7|Programa Vostok|https://liferay.design/events/tramontana-presentation-sep-2019/|404|
|9|https://liferay.design/team/jeong-christopher|Christopher JeongSenior Product Designer||404|
|10|https://www.wallpaper.com/%5D|Wallpaper Magazine|https://liferay.design/team/pires-felipe/|404|
|11|https://help.figma.com/article/47-sharing-files-and-projects|see Figma’s documentation|https://liferay.design/handbook/tools/figma/|404|
|12|slack://user|#t-design-github|https://liferay.design/handbook/tools/github/introduction/|bad url|
|13|https://liferay.design/handbook/work/introduction|||404|
|14|https://www.uie.com/brainsparks/2011/10/27/moving-from-critical-review-to-critique/||https://liferay.design/handbook/collaborate/locally/critique/|404|
|15|https://liferay.design/lexicon/news/updates|||404|
|16|https://clayui.com/docs/layout/grid.html|View in Clay|https://liferay.design/lexicon/foundations/grid/|404|
|17|https://liferay.design/team/balbas-cassandra|Cassandra Balbas|https://liferay.design/articles/2018/81-days-of-liferay/|404|
|18|https://liferay.design/team/wood-jon/iempty.tooliphone.net|this site||404|
|19|https://liferay.design/articles/2019/updates-to-rotisserie|Paul&#x27;s blog entry|https://liferay.design/handbook/collaborate/locally/forum/|404|
|20|https://liferay.design/handbook/grow/transversal-skills|transversal skills|https://liferay.design/handbook/grow/introduction/|404|
|21|https://liferay.design/handbook/grow/product-design/introduction|See Product Design Skills|https://liferay.design/handbook/grow/introduction/|404|
|22|https://liferay.design/handbook/grow/transversal-skills/introduction|transversal skills|https://liferay.design/handbook/grow/career-paths/evaluations/|404|
|23|https://liferay.design/handbook/grow/transversal-skills/excellence|Go to all Excellence Milestones|https://liferay.design/handbook/grow/core-skills/|404|
|24|https://liferay.design/handbook/grow/transversal-skills/collaboration|Go to all Collaboration Milestones|https://liferay.design/handbook/grow/core-skills/|404|
|25|https://liferay.design/handbook/grow/transversal-skills/impact|Go to all Impact Milestones|https://liferay.design/handbook/grow/core-skills/|404|
|26|https://liferay.design/handbook/grow/transversal-skills/advocacy|Go to all Advocacy Milestones|https://liferay.design/handbook/grow/core-skills/|404|
|27|https://liferay.design/handbook/grow/transversal-skills/influence|Go to all Influence Milestones|https://liferay.design/handbook/grow/core-skills/|404|
|28|https://liferay.design/handbook/grow/communication-design/strategy|Go to all Strategy Milestones|https://liferay.design/handbook/grow/communication-design/|404|
|29|https://liferay.design/handbook/grow/communication-design/environmental|Go to all Environmental Milestones|https://liferay.design/handbook/grow/communication-design/|404|
|30|https://liferay.design/handbook/grow/communication-design/production|Go to all Production Milestones|https://liferay.design/handbook/grow/communication-design/|404|
|31|https://liferay.design/handbook/grow/communication-design/brand-identity|Go to all Brand Identity Milestones|https://liferay.design/handbook/grow/communication-design/|404|
|32|https://liferay.design/handbook/grow/communication-design/media|Go to all Media Milestones|https://liferay.design/handbook/grow/communication-design/|404|
|33|https://liferay.design/handbook/grow/product-design/strategy|Go to all Strategy Milestones|https://liferay.design/handbook/grow/product-design/|404|
|34|https://liferay.design/handbook/grow/product-design/research|Go to all Research Milestones|https://liferay.design/handbook/grow/product-design/|404|
|35|https://liferay.design/handbook/grow/product-design/interaction|Go to all Interaction Milestones|https://liferay.design/handbook/grow/product-design/|404|
|36|https://liferay.design/handbook/grow/product-design/visual|Go to all Visual Milestones|https://liferay.design/handbook/grow/product-design/|404|
|37|https://liferay.design/handbook/grow/product-design/engineering|Go to all Engineering Milestones|https://liferay.design/handbook/grow/product-design/|404|
|38|https://liferay.design/pull-requests|pull request guidelines|https://liferay.design/handbook/contribute/issues/|404|
|39|https://liferay.design/principles/Am%20I%20using%20the%20correct%20affordances%20to%20solve%20the%20problem?|affordances||404|
|40|https://clayui.com/docs/components/badges.html|View in Clay|https://liferay.design/lexicon/core-components/badges/|404|
|41|https://clayui.com/docs/components/cards.html|View in Clay|https://liferay.design/lexicon/core-components/cards/|404|
|42|https://clayui.com/docs/components/charts/basic/bar_chart.html|View in Clay|https://liferay.design/lexicon/core-components/charts/chart-bar/|404|
|43|https://clayui.com/docs/components/charts/basic/donut_chart.html|View in Clay|https://liferay.design/lexicon/core-components/charts/chart-doughnut/|404|
|44|https://clayui.com/docs/components/charts/advanced/predictive-forecasting.html|View in Clay|https://liferay.design/lexicon/core-components/charts/chart-forecast/|404|
|45|https://clayui.com/docs/components/charts/basic/pie_chart.html|View in Clay|https://liferay.design/lexicon/core-components/charts/chart-pie/|404|
|46|https://clayui.com/docs/components/dataset-display.html|View in Clay|https://liferay.design/lexicon/core-components/dataset-display/|404|
|47|https://clayui.com/docs/components/dropdowns.html|View in Clay|https://liferay.design/lexicon/core-components/dropdowns/|404|
|48|https://clayui.com/docs/components/forms/form-elements.html|View in Clay|https://liferay.design/lexicon/core-components/forms/|404|
|49|https://clayui.com/docs/components/forms/forms-hierarchy.html|View in Clay|https://liferay.design/lexicon/core-components/forms/forms-hierarchy/|404|
|50|https://clayui.com/docs/components/forms/forms-navigation.html|View in Clay|https://liferay.design/lexicon/core-components/forms/forms-navigation/|404|
|51|https://clayui.com/docs/components/forms/radio-check-toggle.html|View in Clay|https://liferay.design/lexicon/core-components/forms/radio-check-toggle/|404|
|52|https://clayui.com/docs/components/forms/multi-step-form.html|View in Clay|https://liferay.design/lexicon/core-components/forms/multi-step-form/|404|
|53|https://clayui.com/docs/components/forms/multi-step-form-simplified.html|View in Clay|https://liferay.design/lexicon/core-components/forms/multi-step-form-simplified/|404|
|54|https://clayui.com/docs/components/forms/selector.html|View in Clay|https://liferay.design/lexicon/core-components/forms/selector/|404|
|55|https://clayui.com/docs/components/forms/text-input.html|View in Clay|https://liferay.design/lexicon/core-components/forms/text-input/|404|
|56|https://clayui.com/docs/components/forms/text-input-group.html|View in Clay|https://liferay.design/lexicon/core-components/forms/text-input-group/|404|
|57|https://clayui.com/docs/components/forms/text-input-localizable.html|View in Clay|https://liferay.design/lexicon/core-components/forms/text-input-localizable/|404|
|58|https://clayui.com/docs/components/forms/text-input-variations.html|View in Clay|https://liferay.design/lexicon/core-components/forms/text-input-variations/|404|
|59|https://clayui.com/docs/components/icons.html|View in Clay|https://liferay.design/lexicon/core-components/icons/|404|
|60|https://clayui.com/docs/components/labels.html|View in Clay|https://liferay.design/lexicon/core-components/labels/|404|
|61|https://clayui.com/docs/components/modals.html|View in Clay|https://liferay.design/lexicon/core-components/modals/|404|
|62|https://clayui.com/docs/components/navigation/navbar.html|View in Clay|https://liferay.design/lexicon/core-components/navigation/horizontal-nav/|404|
|63|https://clayui.com/docs/components/popovers.html|View in Clay|https://liferay.design/lexicon/core-components/popovers-tooltips/|404|
|64|https://clayui.com/docs/components/progress-bars.html|View in Clay|https://liferay.design/lexicon/core-components/progress-bars/|404|
|65|https://clayui.com/docs/components/stickers.html|View in Clay|https://liferay.design/lexicon/core-components/stickers/|404|
|66|https://clayui.com/docs/components/table/table.html|View in Clay|https://liferay.design/lexicon/core-components/table/|404|
|67|https://clayui.com/docs/css-framework/satellites/timelines.html|View in Clay|https://liferay.design/lexicon/core-components/timelines/|404|
|68|https://clayui.com/docs/components/toolbars/management-toolbar.html|View in Clay|https://liferay.design/lexicon/core-components/toolbars/management-bar/|404|
|69|https://clayui.com/docs/css-framework/satellites/navigation/header.html|View in Clay|https://liferay.design/lexicon/satellite-components/navigation/control-bar/|404|
|70|https://clayui.com/docs/components/sidebar/info-panel.html|View in Clay|https://liferay.design/lexicon/satellite-components/sidebar/infopanel/|404|
|71|https://github.com/liferay-design/lexicon/issues|GitHub repo||404|
|72|https://liferay.design/articles/2019/gestalt-principles/|Gestalt Principles|https://liferay.design/articles/best-practices/measured-vs-optical-alignment/|404|
|73|https://liferay.design/articles/ethics-in-design|post on Ethics|https://liferay.design/articles/best-practices/dark-patterns/|404|
|74|https://liferay.design/team/kolodziej-karolina|Karolina Kolodziej|https://liferay.design/articles/best-practices/service-design/|404|
|75|https://liferay.design/web/guest/home/-/loop/people/_patrick.pentz|Patrick Pentz|https://liferay.design/articles/best-practices/illusion-of-completeness/|404|
|76|https://liferay.design/tags/ResearchAndDevelopment|#ResearchAndDevelopment|https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|77|https://liferay.design/tags/Design|#Design|https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|78|https://liferay.design/tags/VisualDesign|#VisualDesign|https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|79|https://liferay.design/tags/InsideEngineering|#InsideEngineering|https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|80|https://liferay.design/tags/BugbeeFeedback|#BugbeeFeedback|https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|81|https://liferay.design/lexicon/core-components/chart-stacked-bar|Stacked Bar Chart|https://liferay.design/lexicon/core-components/charts/|404|
|82|https://liferay.design/lexicon/core-components/navigation/breadcrub.html|breadcrumb|https://liferay.design/lexicon/core-components/navigation/|404|
|83|https://liferay.design/lexicon/core-components/navigation/.vertical-nav.html|vertically|https://liferay.design/lexicon/core-components/navigation/|404|
|84|https://liferay.design/lexicon/core-components/navigation/.horizontal-nav.html|bars|https://liferay.design/lexicon/core-components/navigation/|404|
|85|https://liferay.design/lexicon/satellite-components/sites/buttons/assetToolbar|Asset Toolbar|https://liferay.design/lexicon/satellite-components/sites/buttons/|404|
|86|https://liferay.design/lexicon/satellite-components/sites/buttons/assetTitleBar|Asset Title Bar documentation|https://liferay.design/lexicon/satellite-components/sites/buttons/|404|
|87|https://liferay.design/handbook/grow/career-paths/overview/|Read about it in our Handbook||404|
|88|https://liferay.design/lexicon-1/patterns/management_bar|management bars|https://liferay.design/lexicon-1/patterns/buttons/|404|
|89|https://liferay.design/lexicon-1/patterns/list|list|https://liferay.design/lexicon-1/patterns/dataset-display/|404|
|90|https://liferay.design/lexicon-1/patterns/card|card|https://liferay.design/lexicon-1/patterns/dataset-display/|404|

**Comment by plhnk** [comment]
Referring page | UR | Int. | Ext. | Anchor and link
-- | -- | -- | -- | --
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/badges/ | 11 | 127 | 19 | VIEW IN CLAYclayui.com/docs/components/badges.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/icons/ | 11 | 127 | 24 | VIEW IN CLAYclayui.com/docs/components/icons.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/cards/cards-variation/ | 11 | 127 | 19 | VIEW IN CLAYclayui.com/docs/components/cards.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/careers/latam/product-designer/ | 11 | 11 | 22 | NOFOLLOWIn case we forgot anything, Seth Godin’s list should cover it :)seths.blog/2018/04/missing-from-your-job-office/404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/forms/text-input-localizable/ | 10 | 107 | 19 | VIEW IN CLAYclayui.com/docs/components/forms/text-input-localizable.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/forms/radio-check-toggle/ | 10 | 127 | 19 | VIEW IN CLAYclayui.com/docs/components/forms/radio-check-toggle.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/toolbars/management-bar/ | 10 | 107 | 19 | VIEW IN CLAYclayui.com/docs/components/toolbars/management-toolbar.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/forms/multi-step-form-simplified/ | 10 | 127 | 19 | VIEW IN CLAYclayui.com/docs/components/forms/multi-step-form-simplified.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/dropdowns/ | 10 | 127 | 19 | VIEW IN CLAYclayui.com/docs/components/dropdowns.html404 NOT FOUND
Liferay Design \| Articles, Events, and Resources for the Open Source Design Communityliferay.design/lexicon/core-components/forms/text-input/ | 10 | 106 | 19 | VIEW IN CLAYclayui.com/docs/components/forms/text-input.html

**Comment by plhnk** [comment]
|||||||
|--- |--- |--- |--- |--- |--- |
|#|Done?|link|Link Text|Page where found|Server response|
|1|[ ]|https://www.liferay.com/404||https://liferay.design/articles/2019/increasing-our-ability-to-convert-prospects/|404|
|2|[ ]|https://assets-liferaydotdesign.wedeploy.io||https://liferay.design/articles/2019/netlify-vs-zeit-vs-github-pages/|bad host|
|3|[ ]|https://wedeploy.com/blog/discontinuing-wedeploy/||https://liferay.design/articles/2019/netlify-vs-zeit-vs-github-pages/|404|
|4|[ ]|https://help.figma.com/category/87-prototyping||https://liferay.design/articles/2019/how-to-use-any-clicker-with-figma-presentations/|404|
|5|[ ]|htttp://www.lexicondesign.io||https://liferay.design/articles/2018/year-one-retrospective-cj/|bad url|
|6|[ ]|https://www.radicalcandor.com/blog/tag/tip/||https://liferay.design/articles/2018/new-team-assemble/|404|
|7|[ ]|https://seths.blog/2018/04/missing-from-your-job-office/||https://liferay.design/careers/latam/product-designer/|404|
|8|[ ]|http://www.terremoto.net/pv7||https://liferay.design/events/tramontana-presentation-sep-2019/|404|
|9|[ ]|https://liferay.design/team/jeong-christopher|||404|
|10|[ ]|https://www.wallpaper.com/%5D||https://liferay.design/team/pires-felipe/|404|
|11|[ ]|https://help.figma.com/article/47-sharing-files-and-projects||https://liferay.design/handbook/tools/figma/|404|
|12|[ ]|slack://user||https://liferay.design/handbook/tools/github/introduction/|bad url|
|13|[ ]|https://liferay.design/handbook/work/introduction|||404|
|14|[ ]|https://www.uie.com/brainsparks/2011/10/27/moving-from-critical-review-to-critique/||https://liferay.design/handbook/collaborate/locally/critique/|404|
|15|[ ]|https://liferay.design/lexicon/news/updates|||404|
|16|[ ]|https://clayui.com/docs/layout/grid.html||https://liferay.design/lexicon/foundations/grid/|404|
|17|[ ]|https://liferay.design/team/balbas-cassandra||https://liferay.design/articles/2018/81-days-of-liferay/|404|
|18|[ ]|https://liferay.design/team/wood-jon/iempty.tooliphone.net|||404|
|19|[ ]|https://liferay.design/articles/2019/updates-to-rotisserie||https://liferay.design/handbook/collaborate/locally/forum/|404|
|20|[ ]|https://liferay.design/handbook/grow/transversal-skills||https://liferay.design/handbook/grow/introduction/|404|
|21|[ ]|https://liferay.design/handbook/grow/product-design/introduction||https://liferay.design/handbook/grow/introduction/|404|
|22|[ ]|https://liferay.design/handbook/grow/transversal-skills/introduction||https://liferay.design/handbook/grow/career-paths/evaluations/|404|
|23|[ ]|https://liferay.design/handbook/grow/transversal-skills/excellence||https://liferay.design/handbook/grow/core-skills/|404|
|24|[ ]|https://liferay.design/handbook/grow/transversal-skills/collaboration||https://liferay.design/handbook/grow/core-skills/|404|
|25|[ ]|https://liferay.design/handbook/grow/transversal-skills/impact||https://liferay.design/handbook/grow/core-skills/|404|
|26|[ ]|https://liferay.design/handbook/grow/transversal-skills/advocacy||https://liferay.design/handbook/grow/core-skills/|404|
|27|[ ]|https://liferay.design/handbook/grow/transversal-skills/influence||https://liferay.design/handbook/grow/core-skills/|404|
|28|[ ]|https://liferay.design/handbook/grow/communication-design/strategy||https://liferay.design/handbook/grow/communication-design/|404|
|29|[ ]|https://liferay.design/handbook/grow/communication-design/environmental||https://liferay.design/handbook/grow/communication-design/|404|
|30|[ ]|https://liferay.design/handbook/grow/communication-design/production||https://liferay.design/handbook/grow/communication-design/|404|
|31|[ ]|https://liferay.design/handbook/grow/communication-design/brand-identity||https://liferay.design/handbook/grow/communication-design/|404|
|32|[ ]|https://liferay.design/handbook/grow/communication-design/media||https://liferay.design/handbook/grow/communication-design/|404|
|33|[ ]|https://liferay.design/handbook/grow/product-design/strategy||https://liferay.design/handbook/grow/product-design/|404|
|34|[ ]|https://liferay.design/handbook/grow/product-design/research||https://liferay.design/handbook/grow/product-design/|404|
|35|[ ]|https://liferay.design/handbook/grow/product-design/interaction||https://liferay.design/handbook/grow/product-design/|404|
|36|[ ]|https://liferay.design/handbook/grow/product-design/visual||https://liferay.design/handbook/grow/product-design/|404|
|37|[ ]|https://liferay.design/handbook/grow/product-design/engineering||https://liferay.design/handbook/grow/product-design/|404|
|38|[ ]|https://liferay.design/pull-requests||https://liferay.design/handbook/contribute/issues/|404|
|39|[ ]|https://liferay.design/principles/Am%20I%20using%20the%20correct%20affordances%20to%20solve%20the%20problem?|||404|
|40|[ ]|https://clayui.com/docs/components/badges.html||https://liferay.design/lexicon/core-components/badges/|404|
|41|[ ]|https://clayui.com/docs/components/cards.html||https://liferay.design/lexicon/core-components/cards/|404|
|42|[ ]|https://clayui.com/docs/components/charts/basic/bar_chart.html||https://liferay.design/lexicon/core-components/charts/chart-bar/|404|
|43|[ ]|https://clayui.com/docs/components/charts/basic/donut_chart.html||https://liferay.design/lexicon/core-components/charts/chart-doughnut/|404|
|44|[ ]|https://clayui.com/docs/components/charts/advanced/predictive-forecasting.html||https://liferay.design/lexicon/core-components/charts/chart-forecast/|404|
|45|[ ]|https://clayui.com/docs/components/charts/basic/pie_chart.html||https://liferay.design/lexicon/core-components/charts/chart-pie/|404|
|46|[ ]|https://clayui.com/docs/components/dataset-display.html||https://liferay.design/lexicon/core-components/dataset-display/|404|
|47|[ ]|https://clayui.com/docs/components/dropdowns.html||https://liferay.design/lexicon/core-components/dropdowns/|404|
|48|[ ]|https://clayui.com/docs/components/forms/form-elements.html||https://liferay.design/lexicon/core-components/forms/|404|
|49|[ ]|https://clayui.com/docs/components/forms/forms-hierarchy.html||https://liferay.design/lexicon/core-components/forms/forms-hierarchy/|404|
|50|[ ]|https://clayui.com/docs/components/forms/forms-navigation.html||https://liferay.design/lexicon/core-components/forms/forms-navigation/|404|
|51|[ ]|https://clayui.com/docs/components/forms/radio-check-toggle.html||https://liferay.design/lexicon/core-components/forms/radio-check-toggle/|404|
|52|[ ]|https://clayui.com/docs/components/forms/multi-step-form.html||https://liferay.design/lexicon/core-components/forms/multi-step-form/|404|
|53|[ ]|https://clayui.com/docs/components/forms/multi-step-form-simplified.html||https://liferay.design/lexicon/core-components/forms/multi-step-form-simplified/|404|
|54|[ ]|https://clayui.com/docs/components/forms/selector.html||https://liferay.design/lexicon/core-components/forms/selector/|404|
|55|[ ]|https://clayui.com/docs/components/forms/text-input.html||https://liferay.design/lexicon/core-components/forms/text-input/|404|
|56|[ ]|https://clayui.com/docs/components/forms/text-input-group.html||https://liferay.design/lexicon/core-components/forms/text-input-group/|404|
|57|[ ]|https://clayui.com/docs/components/forms/text-input-localizable.html||https://liferay.design/lexicon/core-components/forms/text-input-localizable/|404|
|58|[ ]|https://clayui.com/docs/components/forms/text-input-variations.html||https://liferay.design/lexicon/core-components/forms/text-input-variations/|404|
|59|[ ]|https://clayui.com/docs/components/icons.html||https://liferay.design/lexicon/core-components/icons/|404|
|60|[ ]|https://clayui.com/docs/components/labels.html||https://liferay.design/lexicon/core-components/labels/|404|
|61|[ ]|https://clayui.com/docs/components/modals.html||https://liferay.design/lexicon/core-components/modals/|404|
|62|[ ]|https://clayui.com/docs/components/navigation/navbar.html||https://liferay.design/lexicon/core-components/navigation/horizontal-nav/|404|
|63|[ ]|https://clayui.com/docs/components/popovers.html||https://liferay.design/lexicon/core-components/popovers-tooltips/|404|
|64|[ ]|https://clayui.com/docs/components/progress-bars.html||https://liferay.design/lexicon/core-components/progress-bars/|404|
|65|[ ]|https://clayui.com/docs/components/stickers.html||https://liferay.design/lexicon/core-components/stickers/|404|
|66|[ ]|https://clayui.com/docs/components/table/table.html||https://liferay.design/lexicon/core-components/table/|404|
|67|[ ]|https://clayui.com/docs/css-framework/satellites/timelines.html||https://liferay.design/lexicon/core-components/timelines/|404|
|68|[ ]|https://clayui.com/docs/components/toolbars/management-toolbar.html||https://liferay.design/lexicon/core-components/toolbars/management-bar/|404|
|69|[ ]|https://clayui.com/docs/css-framework/satellites/navigation/header.html||https://liferay.design/lexicon/satellite-components/navigation/control-bar/|404|
|70|[ ]|https://clayui.com/docs/components/sidebar/info-panel.html||https://liferay.design/lexicon/satellite-components/sidebar/infopanel/|404|
|71|[ ]|https://github.com/liferay-design/lexicon/issues|||404|
|72|[ ]|https://liferay.design/articles/2019/gestalt-principles/||https://liferay.design/articles/best-practices/measured-vs-optical-alignment/|404|
|73|[ ]|https://liferay.design/articles/ethics-in-design||https://liferay.design/articles/best-practices/dark-patterns/|404|
|74|[ ]|https://liferay.design/team/kolodziej-karolina||https://liferay.design/articles/best-practices/service-design/|404|
|75|[ ]|https://liferay.design/web/guest/home/-/loop/people/_patrick.pentz||https://liferay.design/articles/best-practices/illusion-of-completeness/|404|
|76|[ ]|https://liferay.design/tags/ResearchAndDevelopment||https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|77|[ ]|https://liferay.design/tags/Design||https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|78|[ ]|https://liferay.design/tags/VisualDesign||https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|79|[ ]|https://liferay.design/tags/InsideEngineering||https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|80|[ ]|https://liferay.design/tags/BugbeeFeedback||https://liferay.design/articles/best-practices/introducing-designbestpractices/|404|
|81|[ ]|https://liferay.design/lexicon/core-components/chart-stacked-bar||https://liferay.design/lexicon/core-components/charts/|404|
|82|[ ]|https://liferay.design/lexicon/core-components/navigation/breadcrub.html||https://liferay.design/lexicon/core-components/navigation/|404|
|83|[ ]|https://liferay.design/lexicon/core-components/navigation/.vertical-nav.html||https://liferay.design/lexicon/core-components/navigation/|404|
|84|[ ]|https://liferay.design/lexicon/core-components/navigation/.horizontal-nav.html||https://liferay.design/lexicon/core-components/navigation/|404|
|85|[ ]|https://liferay.design/lexicon/satellite-components/sites/buttons/assetToolbar||https://liferay.design/lexicon/satellite-components/sites/buttons/|404|
|86|[ ]|https://liferay.design/lexicon/satellite-components/sites/buttons/assetTitleBar||https://liferay.design/lexicon/satellite-components/sites/buttons/|404|
|87|[ ]|https://liferay.design/handbook/grow/career-paths/overview/|||404|
|88|[ ]|https://liferay.design/lexicon-1/patterns/management_bar||https://liferay.design/lexicon-1/patterns/buttons/|404|
|89|[ ]|https://liferay.design/lexicon-1/patterns/list||https://liferay.design/lexicon-1/patterns/dataset-display/|404|
|90|[ ]|https://liferay.design/lexicon-1/patterns/card||https://liferay.design/lexicon-1/patterns/dataset-display/|404|

**Comment by victorvalle** [comment]
Wow! that is a lot. I will fix it asap.

I've just fixed our links in claysite https://github.com/liferay/clay/pull/2930

**Comment by victorvalle** [comment]
I will fix our links to clay at least

**Comment by victorvalle** [comment]
I've fixed many of the clay links here https://github.com/liferay-design/liferay.design/pull/677
I will have to review more cases
@drakonux

**Comment by plhnk** [comment]
fixed the rest in #780 — the ones for inactive teammates will require more thought, so will close this one out for now
