### ISSUE TITLE
Please add more contents to https://liferay.design/blueprints/resources/

### ISSUE THREAD

**Issue by YoshikazuShimizu** [liferay-design/liferay.design#703]
**Is your request related to a problem? Please describe.**
Could you add more contents to here? https://liferay.design/blueprints/resources/iconography/
There are lots of icons on website (such as https://www.liferay.com/en/products/dxp-cloud) but not on the liferay.design/blueprints/

Also, it’d be great if we have more illustrations, product screenshots, and product animations available (just general ones are enough).**

**Describe the solution you'd like**
Adding more contents.

**Additional context**
It will be very helpful if we have more contents available when creating product pages, proposals, etc.

Please let me know how long it will take. We've been working on creating new pages so we'd like to know how long it will take.

Thank you,

Yoshi

**Comment by plhnk** [comment]
Hi @YoshikazuShimizu — thanks for sending this issue, any content that's available on liferay.com should be accessible in Documents & Media (@abelhancock please correct me if I'm wrong) for use on other pages.

In the meantime, @abelhancock will get these assets up on Blueprints next week.

**Comment by YoshikazuShimizu** [comment]
Thank you @plhnk!

**Comment by abelhancock** [comment]
Hey @YoshikazuShimizu, @naoki-evan-hisamoto and I are working to get all icons available to you very soon (probably EOD). We will move them to a folder in google drive and make it accessible from blueprints (same way we handle our logos currently).
Illustrations and product screenshots will take a little more time but I'll try to get more up on the site by the end of the week.

**Comment by YoshikazuShimizu** [comment]
thank you Abel!
