### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#711]
Now that we're "beyond the hype", I think it's time we looked into using TypeScript. 😄 

@ddprrt's webinar [TypeScript for Smashing People](https://www.smashingmagazine.com/smashing-tv/typescript-for-smashing-people/) was a great intro and helped me understand the value of TS, and how to go about implementing.

## Value of TypeScript (TS)

As I understand it _(warning, take everything (as always) with a grain of salt)_ — TS is an extension of Javascript (JS). Meaning, that you don't actually _need_ to change the way you write JS. But if you want to, you can make it easier for your future self and other people that will work on the project.

[Figma's 'What is TypeScript'](https://www.figma.com/plugin-docs/typescript/) summarizes it quite nicely:
> TypeScript allows you to add type annotations to your code. These don't change how your code runs, they are just notes for yourself and for the compiler

So basically — TS helps you write better, clearer JS. And who doesn't want that!

## Implementation "Strategy"

1. Install the [Gatsby TS plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/) 
1. Check compatibility w/current ESLint setup, [modify as necessary](https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/#eslint)
1. Set up a [type-check task](https://github.com/Microsoft/TypeScript-Babel-Starter)

## How does this affect me?

Moving forward, you'll be able to use TS! You don't _have_ to, but you probably should learn it, seems like it'll make your life a lot easier. Plug Figma uses it for their plugins, and we need some of those.

You may start seeing little lines in your code (like when you misspell words):
![image](https://user-images.githubusercontent.com/10226086/76441337-78ae3a00-637c-11ea-85c1-16db8f2c23dc.png)
These are helpful :)

**Comment by plhnk** [comment]
@jamesjlyons @jonmwood @abelhancock thoughts? questions? protests? 

_(of course welcome any others to chime in, just starting a discussion)_

**Comment by jonmwood** [comment]
that's cool with me 👌

**Comment by plhnk** [comment]
okay all set! type away! 

note — you'll have to `npm install` as there are a couple new packages — I'd recommend running

```
rm -rf node_modules && npm install
```

**Comment by victorvalle** [comment]
Do you already have a code example using TS?

**Comment by ddprrt** [comment]
Just wanted to say that I'm super happy that you found my webinar useful 🙌

**Comment by plhnk** [comment]
> Do you already have a code example using TS?

I haven't written anything new yet — is there something you'd like to see?

@ddprrt :) thank you!
