### ISSUE TITLE
Redesign Figma File Covers

### ISSUE THREAD

**Issue by fapires** [liferay-design/liferay.design#722]
After some time serving us really well, I think it's time to update our Figma cover files.
The idea is to make it simpler, cleaning the unnecessary information up, using emojis to communicate statuses and set of lighter and brighter colors. Also, I removed the `resource` cover once it's not a status, but a deliverable type and a `resource` can have multiple statuses. Plus, I introduced a new `exploration` cover for the initial phases of a new design initiative. 

[Figma File](https://www.figma.com/file/kfPxNkX3sJ7D1S3ZMKXJ2S/covers-redesign?node-id=0%3A1)

**Comment by drakonux** [comment]
Here are my two cents:
- Use of text at all levels. No icons, no effort to understand the icon. 
- Keep it minimalist, focused on the thumbnail view. 
- Try to not repeat the same info that appears in the file name.
- The Information shown should be Flexible for different contexts (product teams, tests, spike, etc)

**Comment by plhnk** [comment]
Hey @fapires thanks for the exploration! Before making comments, just wanted to summarize what I'm seeing :)

## Scope of changes
It seems like there are three areas you're tackling in this exploration:

1. **Procedural** aspects related to covers (deprecating `resource`, introducing `exploration`)
1. **Information architecture** for a cover (removing `Type`, `Contributors`; adding `Issue`)
1. **Visual updates** (adding an emoji, changing colours)

## Value of changes
It sounds like the value provided by these updates will be a simpler view that will make it easier to quickly understand the contents and some basic metadata about the file.

Did I miss anything? Any more to add on the scope or is there a better way to state the value add?

**Comment by fapires** [comment]
I think that all @Paul

Sent via Superhuman ( https://sprh.mn/?vip=felipe.pires@liferay.com )

**Comment by plhnk** [comment]
hey @fapires — replying to your figma comment about next steps here :) — there are a lot of changes in this scope, I think next steps would be to break up the changes into smaller chunks. 

Before you do that, there are a few things I wanted to highlight:

## Procedural
This level of change is beyond simply updating the covers — and should involve more people's thoughts beyond you, me, and David (thanks @drakonux for chiming in!) at the least it should be @victorvalle and @ryconn888 as well.

My brief thoughts on this issue are:
1. You have a good point, `Resource` is a deliverable — however it's not clear to me what cover we would use for resource files moving forward.
  1. Perhaps the label "resource" could be improved — the purpose of them is figma stuff that we'll use in other files
1. `exploration` (at least in my understanding of this step) would fall under the "in design" category — it's unclear the value derived from having that one small part of "in design" highlighted as a status

_Unless there's a clear procedural problem and accompanying solution that provides demonstrable value, I'm not sure it's worth our time to make these procedural changes_

## Information Architecture
1. Per [our discussion in Slack](https://liferay.slack.com/archives/CL2KU6A65/p1587753597023400) a few weeks ago — `Issue` field is unnecessary as it should be in the filename (so its indexed)
1. Agree that `Type` could probably be eliminated, but again, we should get more thoughts — want to make sure we're not deleting something that someone is getting value from.
1. Unsure about removing `Contributors` => can you explain your thoughts/rationale on this?

## Visual Updates
1. I'm in agreement w/@drakonux's suggestion — introducing the icon seems contrary to your goal of simplifying the view — it's an additional element that needs to be parsed, additionally in the current design it causes the status label and story title to be misaligned vertically, which makes it less legible.
1. I could be wrong — but I don't think this is what the [chart colors](https://liferay.design/lexicon/core-components/charts/chart-color-palette) were designed for. To be sure the colors in the original design could/should be updated as I don't think they are referencing the current Lexicon [functional colors](https://liferay.design/lexicon/foundations/color/#secondary-colors).

**Comment by fapires** [comment]
Thanks for letting me know about the points that were not clear for me.
My considerations:
1. Replaced the `Exploration` by `Resouces`
2. Replaced `Issue` by `Contributors`
3. Remove emojis, it's not scalable and adding too much information to the cards
4. Even if was not design do communicate states, I don't think it's a problem to use the chart color, do you?

Let's wait for @victorvalle and @ryconn888 thoughts

**Comment by victorvalle** [comment]
- We don't need "exploration". In the current model we use the field type to define if we are working in a spike (exploration ticket type) or story.
- "Resources" is nice. I would finish some spike tickets as resources as they will help for the future. I have problems to visually identify them.
- More space for author name, and less for contributors. Usually in contributors we write initials. In Stakeholder we write the PM name or team name.
- About colors, I'm ok with whatever decision you take.

**Comment by abelhancock** [comment]
Hi! 👋 Joining this discussion a little late. I just took a look at the new covers and it seems like the only changes are the styling? First, I really like the updated look. But I'm thinking... if we update the covers then we're going to have a mix of covers in figma (or we would have to update all the old files) which seems like it would only be worthwhile if we're adding additional value with the cover update. So I guess my 2 cents at this point is to leave them as they are unless the updated covers are adding additional value. 🤷‍♂️

**Comment by fapires** [comment]
If you think about visual design as a usability tool, I would say we are delivering more than stylish value: we are improving readability, reducing complexity, and improving information hierarchy.

**Comment by abelhancock** [comment]
Yeah that is added value! I think the new covers (where they're at now) reduce complexity and improve information hierarchy. But overall they're quite a bit more difficult to scan at the size we view them a (~300px or less) because of lack of contrast & font size, etc. Maybe if we do improve that it would be value added! But the other side of visual design as usability is that we're introducing two cover styles into our file browser, making it more complex/difficult to scan (which can be solved by updating them all or just over time from phasing them out). I just think should be considered as a cost/trade-off.

**Comment by abelhancock** [comment]
<img width="308" alt="Screen Shot 2020-05-22 at 7 53 34 AM" src="https://user-images.githubusercontent.com/31840274/82681503-b80dc800-9c02-11ea-9a6f-32dac2a2d70e.png">
Again, I'm totally in favor of making improvements 100% of the time haha. Just playing a bit of devils advocate and looking at the implications.

**Comment by plhnk** [comment]
Good point about usability @fapires — I'm surprised @victorvalle didn't mention this 😉, but half of the covers don't pass contrast guidelines:
![image](https://user-images.githubusercontent.com/10226086/82686822-4a19ce80-9c0b-11ea-8ac0-c6707e24f19a.png)

![image](https://user-images.githubusercontent.com/10226086/82686839-50a84600-9c0b-11ea-97fa-ee3d6afeb176.png)

![image](https://user-images.githubusercontent.com/10226086/82686853-56059080-9c0b-11ea-88cc-fb838111828d.png)

I would like to hear @emiliano-cicero's perspective on using chart colors vs [functional colors](https://liferay.design/lexicon/foundations/color/#secondary-colors) — I think he is more suited than I am for this area :)

**Comment by plhnk** [comment]
Also — I appreciate @fapires and @abelhancock discussion on adding value, I think @crystaljuarez3 also had something to say on this regard.. 😄 

If we're going to go to the effort to make this kind of change, it should be a slam dunk — thinking aloud, a problem we could solve is that when a cover is set as a thumbnail (vs used in the old way as a separate page) the aspect ratio is not as responsive as it could be:
<img width="352" alt="Screen Shot 2020-05-22 at 9 15 07 AM" src="https://user-images.githubusercontent.com/10226086/82688356-99f99500-9c0d-11ea-8706-50ec7524badb.png">
<img width="619" alt="Screen Shot 2020-05-22 at 9 14 46 AM" src="https://user-images.githubusercontent.com/10226086/82688359-9a922b80-9c0d-11ea-81c0-18241504e979.png">
Figuring out the optimal ration / sweet zone for content would be very valuable.

Are there other usability problems anyone else has run into w/covers?

**Comment by fapires** [comment]
There is also a new case to cover: pinned files
<img width="315" alt="Screen Shot 2020-05-22 at 14 27 00" src="https://user-images.githubusercontent.com/8724228/82693742-6da73e00-9c38-11ea-81bd-dc2a85880437.png">

**Comment by plhnk** [comment]
@fapires yes — pinned files, good point!

I agree unnecessary complexity should be avoided — but also, to kind of respond to @abelhancock's point, if we're going to all this trouble, then it should be worth it? Seems as things are now, it would be a half-measure. Making visual updates is important and useful — however we could do a little more work and get a lot more value (I think that's what he's saying, please correct if I'm wrong).

**Comment by plhnk** [comment]
*bump bump* — saw [this idea](https://twitter.com/figmadesign/status/1273498175714836481) to add avatars

**Comment by fapires** [comment]
That's nice! "Don't tell me, show me", they say

**Comment by abelhancock** [comment]
**Cover update - Not a redesign**

I updated the covers [here](https://www.figma.com/file/dk8ECobThQm6EWo0PqXeR1/utilities?node-id=223%3A14&viewport=137%2C189%2C0.33072251081466675) to follow [Figma's guidlines](https://help.figma.com/hc/en-us/articles/360038511413-Set-custom-file-thumbnails).

Changes:

- Added 20px width to frames (same ratio as guidelines at 1/3 scale)
- Moved content into "safe" area
- Moved all file info inline to better fit within "safe" area
- Reduced file info text size 2px (to 22px)
- Removed undeeded frames around text
- Applied background color to frame and removed "bg" element
- Added auto layout to file info section

I'll publish these changes in 24hrs if no comments are made.

**Comment by victorvalle** [comment]
Hi @abelhancock ,
I like the changes but why did you increase the left and right margins? Our tasks have pretty long names, that don't benefit us at all.

Thanks!

**Comment by abelhancock** [comment]
@victorvalle I increased the margins to keep the text from being cut off - following the linked Figma guidelines. All the content is inside the "safe zone". You can make the grids visible in the figma file to see where the safe zone is on the artboards.

I've seen that some of your files decrease the font size of the title to fit. We could decrease the default title size a bit &/or just continue to adjust it per file as we are now.

**Comment by abelhancock** [comment]
![image](https://user-images.githubusercontent.com/31840274/90041727-8bf06900-dc7e-11ea-9271-0d0c07472d94.png)

**Comment by victorvalle** [comment]
I think that only happens when the designer makes a frame the cover instead of having the first page as a cover
![image](https://user-images.githubusercontent.com/21121115/90043021-c502fa80-dccb-11ea-8a80-9940f20f4fa2.png)

In that case, I would recommend providing a clear message to all designers on how to proceed with cover.
a. Page as cover
b. Frame as cover

**Comment by victorvalle** [comment]
@emiliano-cicero does option **b**. I do **a**.

**Comment by abelhancock** [comment]
Yes, I do option A as well currently.

The purpose of this change is to make option B the default so that it:
-  Maximizes thumbnail space filled in the file browser (fonts appear larger)
-  In the file browser, the entire thumbnail will fill with the cover color so that the "cover" page doesn't create a white/gray border around the thumbnail

For myself, I will still use a "cover" page but then set the frame as the thumbnail.

**Comment by plhnk** [comment]
closing this issue due to 🦗 🦗 🦗
