### ISSUE TITLE
Different background-color in Lexicon landing page

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#727]
**Description**
I see different blue background-colors for Chromium browsers. 

**Firefox 75.0 (64-bit)**
![image](https://user-images.githubusercontent.com/21216422/80510510-1c7a9600-897b-11ea-8232-2faa6aaf4ec5.png)

**Edge Versión 81.0.416.64 (64 bits)**
![image](https://user-images.githubusercontent.com/21216422/80510547-29978500-897b-11ea-9144-6833419e068b.png)

**Chrome Versión 81.0.4044.129 (64 bits)**
![image](https://user-images.githubusercontent.com/21216422/80510578-374d0a80-897b-11ea-9109-b6898e8f977b.png)

**Expected Behavior**
Same background-color visiting Lexicon Site with any browser.

**Comment by plhnk** [comment]
is this an issue with the site or with how colors are rendered on different browsers in different operating systems?

**Comment by plhnk** [comment]
seems like a [known issue](https://webmasters.stackexchange.com/questions/15283/google-chrome-for-mac-css-colors-and-display-profiles) — do you think it is worth figuring out a solution?

**Comment by plhnk** [comment]
per a side-chat w/ @drakonux:
> This year we will change the Lexicon site and my idea is to rid the landing page.
