### ISSUE TITLE
Blueprints - Iconography, SVG Google Drive links to an empty folder

### ISSUE THREAD

**Issue by MarkusHmr** [liferay-design/liferay.design#735]
When clicking on:
"Browse SVG Icons, Open in Google Drive" you get lead to an empty g-drive folder.

**Comment by victorvalle** [comment]
@MarkusHmr this is not a technical issue. Someone from the team must bring the icons into the folder.
Maybe @plhnk or @emilyyoung know who is in charge of these icons

**Comment by MarkusHmr** [comment]
Oh Okay, good to know. Maybe @naoki-evan-hisamoto or @abelhancock do have the svgs?

**Comment by plhnk** [comment]
tagging @naoki-evan-hisamoto — I believe he's the original creator of the folder, from what I can tell it looks like the svg's never actually synced in? Maybe I'm reading the activity history incorrectly. thx!

**Comment by naoki-evan-hisamoto** [comment]
@abelhancock is actually the original creator of the folders. As far as I know though, the SVG's were never synced. Where we left off, many of the SVG's still need to be cleaned up and we are still missing a type of naming convention.

**Comment by plhnk** [comment]
thanks for the update @naoki-evan-hisamoto — if you guys could get those synced as-is so there's something in the folder that would be appreciated! (I know @corbinmurakami will be most grateful --> #736)

**Comment by MarkusHmr** [comment]
Yes, i was just curious why we link to an empty folder rather then removing the link to it :)

**Comment by naoki-evan-hisamoto** [comment]
@MarkusHmr The first batch has been uploaded!
