### ISSUE TITLE
The Liferay Blueprints iconography page links to an empty Google Drive folder

### ISSUE THREAD

**Issue by corbinmurakami** [liferay-design/liferay.design#736]
**Describe the bug**
The Liferay Blueprints iconography page links to an empty Google Drive folder.

**To Reproduce**

1. Go to https://liferay.design/blueprints/resources/iconography/
2. Click on Browse SVG Icons → Open in Google Drive

**Expected behavior**
Google Drive folder contains SVG versions of icons

**Screenshots**
<img width="1155" alt="Screen Shot 2020-05-28 at 6 56 38 PM" src="https://user-images.githubusercontent.com/12375618/83212678-f92b3e00-a114-11ea-9445-58cbb0bb118d.png">

**Comment by plhnk** [comment]
Thanks for filing @corbinmurakami, please see #735
