### ISSUE TITLE
Need to remove James Lyons from Team

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#737]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone X]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by victorvalle** [comment]
Set to inactive https://github.com/liferay-design/liferay.design/pull/740
