### ISSUE TITLE
Design System into Figma Communities

### ISSUE THREAD

**Issue by jcusick93** [liferay-design/liferay.design#754]
Hi Team - I recently launched www.designsystemsforfigma.com and would love it if you could move your Figma files into Figma communities and I can link to that :)

--> https://www.figma.com/blog/introducing-figma-community/

**Comment by plhnk** [comment]
hey @jcusick93 thanks for the highlight! 

We do have Lexicon published on our [community profile page](https://www.figma.com/@liferay) — let me know if there's anything else we could/should add!

**Comment by plhnk** [comment]
(going to leave this issue open — we should add the community profile to our website :) )

**Comment by jcusick93** [comment]
that would be great :) I will update my website with your link.
https://designsystemsforfigma.com/

**Comment by plhnk** [comment]
thanks again for writing this issue @jcusick93  — we've got a link to our Figma profile in the footer now 👍
