### ISSUE TITLE
Broken image in the Text Input Group article

### ISSUE THREAD

**Issue by corbinmurakami** [liferay-design/liferay.design#774]
**Describe the bug**
There is a broken image in the Text Input Group article

**To Reproduce**

1. Go to 'https://liferay.design/lexicon/core-components/forms/text-input-group/'
2. Go to the "Input group with units" section
3. See that there is a broken image (/images/lexicon/InputGroupAddonLeftplaceholder.png)

**Expected behavior**
No broken image

**Desktop (please complete the following information):**

-   Browser Chrome latest

**Comment by plhnk** [comment]
thanks for filing @corbinmurakami

**Comment by victorvalle** [comment]
Solved! https://github.com/liferay-design/liferay.design/pull/776
