### ISSUE TITLE
Search double help mobile

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#779]
I get to help messages that overlap each other in mobile.

**Comment by plhnk** [comment]
can you add a screenshot?

**Comment by victorvalle** [comment]
![IMG_4002](https://user-images.githubusercontent.com/21121115/92034416-7d710b00-ed6d-11ea-9b81-77f9b024415e.PNG)

**Comment by plhnk** [comment]
oh thats really weird, thanks I'll try to reproduce

**Comment by victorvalle** [comment]
I think I wrote something impossible to find and tapped twice

**Comment by plhnk** [comment]
is this still happening @victorvalle ? is it worth the effort to fix?
