### ISSUE TITLE
Digital Color url is broken

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#787]
https://liferay.design/docs/resources/color/digital.html

Getting a 404

**Comment by plhnk** [comment]
Where is this link coming from? Are you looking for [this page](https://liferay.design/blueprints/guidelines/color/digital/)?

**Comment by victorvalle** [comment]
I was going to answer the same. @ryconn888 maybe your link is old

**Comment by ryconn888** [comment]
It's from this page - https://liferay.design/blueprints/guidelines/color/
The link that says 'Digital Color Resources' within the page content -- under the paragraph 'Liferay Blue'

**Comment by plhnk** [comment]
ok will fix in #786

**Comment by plhnk** [comment]
added in #786
