### ISSUE TITLE
Add Resource Thumbnails to blueprints

### ISSUE THREAD

**Issue by abelhancock** [liferay-design/liferay.design#790]
**Describe the solution you'd like**
Add a new category called "Resource Thumbnails" to Blueprints > Resources > Illustrations. Add link/card similar to the icon cards in the section that directs to the [drive folder](https://drive.google.com/drive/folders/15LjS6o3xmGu_zjnHim_LHhFbINGs_6w2?usp=sharing)

Use this [image](https://drive.google.com/open?id=16ilR0O5jYoAsGWS78rFZnqLgyTUba9E2&authuser=abel.hancock%40liferay.com&usp=drive_fs) for the card.

**Comment by plhnk** [comment]
added in #786
