### ISSUE TITLE
Add Analytics Cloud screenshots

### ISSUE THREAD

**Issue by christinereyes** [liferay-design/liferay.design#793]
Please add these product screenshots for Analytics Cloud.

- [x] Links to assets / content: https://www.figma.com/file/xfHVip5z6eiyXIB0H4Mo1h/Screenshots?node-id=0%3A1
- [x] Brief description of the content: Updated product screenshots for Analytics Cloud. There are two titled "page dash," but the second one is actually showing Form Analytics.
- [x] _optional_ Requested location (e.g. Resources > Illustrations): Resources > Product Screenshots

**Comment by plhnk** [comment]
fixed in #794
