### ISSUE TITLE
Counter Increment at 10+ breaks styling (Management page in Career Paths)

### ISSUE THREAD

**Issue by jonmwood** [liferay-design/liferay.design#805]
**Describe the bug**
When viewing the numbered list in the Management page the counter increment at 10+ (double digits) breaks styling and wraps the number.

**To Reproduce**

1. Go to [Management page](https://liferay.design/handbook/grow/career-paths/management/)
2. Scroll down to 10, 11, 12 numbered list
4. It's breaking/wrapping bc of the width is set for single digits.

**Expected behavior**
read 10, 11 ... as normal :D 

```
 width: 3ch;
 margin-left: -4ch;

```
should do the trick

**Screenshots**
![image](https://user-images.githubusercontent.com/12825083/94699779-9084e580-02ef-11eb-906b-9fb132624ad6.png)

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone X]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by plhnk** [comment]
fixed by #806 — thanks @jonmwood !
