### ISSUE TITLE
Typo in Dual Listbox 

### ISSUE THREAD

**Issue by jonmwood** [liferay-design/liferay.design#808]
_Most Lexicon requests [start in Jira](https://issues.liferay.com/projects/LEXI/issues) — if you're nor part of that team or for some reason can't see the project, create an issue and we'll take it from here._

**Is your request related to a problem? Please describe.**
[on the Dual Listbox page](https://liferay.design/lexicon/core-components/dual-listbox/) the first point there's a typo

> In usex Listbox

**Describe the solution you'd like**
> In usex Listbox

should be In Use Listbox

**Comment by victorvalle** [comment]
Thansk for reporting!
