### ISSUE TITLE
Link Documents to Template Gallery

### ISSUE THREAD

**Issue by Jessikarap** [liferay-design/liferay.design#810]
Page: https://liferay.design/blueprints/resources/documents/
Need to replace the link to our proper Google Drive Templates.

Replace
"Add these templates to your Google Drive."

with

"Access these templates in [Google Docs](https://docs.google.com/).
To display template gallery, go to "Settings" in the menu on the left. Check "Display recent templates..." and click "Ok."
<img width="749" alt="screencap1" src="https://user-images.githubusercontent.com/57199437/94891607-60485e80-0437-11eb-8ca3-6bbe123369b9.png">

Click "Template gallery" on the top right and use any of the approved templates under *Liferay Corporate Templates".
<img width="1405" alt="screencap2" src="https://user-images.githubusercontent.com/57199437/94891611-62aab880-0437-11eb-9f14-5c3e0440b99e.png">
"

Thank you!!

**Comment by plhnk** [comment]
fixed in #811
