### ISSUE TITLE
Chore: Grammar 🤔 in Writing > Style > Punctuation

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#813]
[Punctuation](https://liferay.design/lexicon/foundations/writing/style/#punctuations) is both singular and plural — its possible that this section could be referencing punctuation _marks_, but either way 'punctionations' is not grammatically correct.

**Comment by victorvalle** [comment]
Tech writer didn't say anything about it... 
@cj213x could you review this?
