### ISSUE TITLE
sidebar for blueprints

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#85]
can utilize same design and functionality as it exists live on blueprints.liferay.design (reference clayui.com for most up-to-date code)

this is critical for the blueprints portion of the site, and will also be reused for the design handbook and lexicon portions (in the future).

**Comment by protoEvangelion** [comment]
Desktop styles: https://github.com/liferay-design/liferay.design/pull/99

**Comment by plhnk** [comment]
thanks a ton @protoEvangelion ! works great
