### ISSUE TITLE
Update to Liferay Logos

### ISSUE THREAD

**Issue by Jessikarap** [liferay-design/liferay.design#869]
Hi,

Can you please make the following updates?

1. Resources > Logos
- Update description under "Logos" to "Thoroughly review the [usage guidelines](https://liferay.design/blueprints/guidelines/logo-usage) before applying logos. As recommended by the Liferay Legal Department, please use logos with the registered trademark wherever possible. Contact Legal with any specific questions you may have in regards to your use case."
- Take out "Special Marks" section. 15 years has passed
- Update "Corporate Marks" and "Product Logos" with the current digital registered trademark logos found in the [Google Drive](https://drive.google.com/drive/folders/1aVeCcvZfeT_zqEDBfzzNW8Z8Ey8Wx3yU?usp=sharing). All logos except DXP Cloud should be changed.

2. Guidelines > Logos
- Add description under "Logos" "As recommended by the Liferay Legal Department, please use logos with the registered trademark wherever possible. Contact Legal with any specific questions you may have in regards to your use case. Read more about protecting our trademark [here](https://drive.google.com/file/u/1/d/1CRRUOhwZ7n4DnJ98dpD7g8Og55mAJMdu/view?usp=sharing)."
- All Liferay Logos need to be updated to the Liferay®️.
<img width="681" alt="Screen Shot 2020-11-20 at 2 41 49 PM" src="https://user-images.githubusercontent.com/57199437/101403148-a8e22500-3889-11eb-9f8a-e1f1b67e04ce.png">
<img width="685" alt="Screen Shot 2020-11-20 at 2 42 22 PM" src="https://user-images.githubusercontent.com/57199437/101403150-aa135200-3889-11eb-8d8d-37222243e5e6.png">
<img width="402" alt="Screen Shot 2020-11-20 at 2 43 13 PM" src="https://user-images.githubusercontent.com/57199437/101403153-aa135200-3889-11eb-8ff1-275449b55d17.png">
<img width="292" alt="Screen Shot 2020-11-20 at 2 44 28 PM" src="https://user-images.githubusercontent.com/57199437/101403154-aaabe880-3889-11eb-9129-38534c0ee6e2.png">
<img width="594" alt="Screen Shot 2020-11-20 at 2 51 59 PM" src="https://user-images.githubusercontent.com/57199437/101403160-ab447f00-3889-11eb-868b-14744bb61618.png">
<img width="288" alt="Screen Shot 2020-11-20 at 2 25 09 PM" src="https://user-images.githubusercontent.com/57199437/101403212-c0b9a900-3889-11eb-909b-05c511af2618.png">

Thanks and let me know if you have any questions :)

**Comment by plhnk** [comment]
thanks @Jessikarap !

**Comment by Jessikarap** [comment]
Hi @plhnk, any updates on when this will be completed by? We'd like to let the marketers know the changes as well. Thanks!

**Comment by plhnk** [comment]
- [x] Update description under "Logos" to "Thoroughly review the usage guidelines before applying logos. As recommended by the Liferay Legal Department, please use logos with the registered trademark wherever possible. Contact Legal with any specific questions you may have in regards to your use case."
- [x] Take out "Special Marks" section. 15 years has passed
- [x] Update "Corporate Marks" and "Product Logos" with the current digital registered trademark logos found in the Google Drive. All logos except DXP Cloud should be changed.
- [x] Add description under "Logos" "As recommended by the Liferay Legal Department, please use logos with the registered trademark wherever possible. Contact Legal with any specific questions you may have in regards to your use case. ~Read more about protecting our trademark here.~"
- [ ] All Liferay Logos need to be updated to the Liferay®️.

**Comment by plhnk** [comment]
two quick things:

1. Do you think people will read the USPTO PDF? it's kind of long...is there a summary somewhere or maybe we could distill it down into a few of the most important points?
2. Could you use the same dimensions as the frames in the [Figma brand-assets file](https://www.figma.com/file/b7taYciXEysAiBcsMXvv9nOV/brand-assets?node-id=2302%3A2203)? Both for the resouce card images and the do/dont guidelines

The stuff I've checked off is now live, once we get the other things I'll get it up ASAP.

**Comment by Jessikarap** [comment]
1. Yah, it's long but let's just link that file for now since it's an actual certified document.
2. I attached the files that needs to be updated. Please update DXP Cloud too even though there's no "R".
Thanks!
[Uploading Figma Logos.zip…]()

**Comment by Jessikarap** [comment]
Hi @plhnk,

Are there any updates? When can we see the changes made?

Thanks!

**Comment by plhnk** [comment]
[updates are live](https://liferay.design/blueprints/guidelines/logo-usage) — leaving this issue open to fix:

- [ ] update image reference for Liferay logo in 2nd example (missing ®)
- [ ] update ordered list so that its actually numbering (currently all 1's)

will fix those next week.

**Comment by Jessikarap** [comment]
Thanks for all the help. Please let me know if you need anything else from me!
