### ISSUE TITLE
Utilize react components in the markdown files

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#89]
**Describe the solution you'd like**
When create markdown pages, I'd like to be able to call some components (i.e. cards for all the colors) so I don't have to write a bunch of html

[mdxjs](https://mdxjs.com/) seems to be the preferred library for Gatsby, but open to strong contenders.

**Describe alternatives you've considered**
Having the components render on a sample page, then copying/pasting the html into markdown

**Comment by protoEvangelion** [comment]
I've been eyeing mdx for this: https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/?no-cache=1

**Comment by protoEvangelion** [comment]
https://mdxjs.com/

**Comment by plhnk** [comment]
Isn't this the same thing? (install looks the same: https://mdxjs.com/getting-started/gatsby)

I tried it a few weeks ago, but got some errors and gave up pretty quickly.....

**Comment by protoEvangelion** [comment]
It's alive! #108
