### ISSUE TITLE
Scrollbars are not visible on the entire site

### ISSUE THREAD

**Issue by drakonux** [liferay-design/liferay.design#892]
Scrollbars are not shown in several browsers. There is one exception, using Firefox on the side panel in the Lexicon Site, see the last comment of https://github.com/liferay-design/liferay.design/issues/660

**Steps to Reproduce**
Go to [liferay.design](https://liferay.design/)

**PC (64bits) WINDOWS 10 v1863.1256** 

*Edge v87.0.664.75*

![edge](https://user-images.githubusercontent.com/21216422/104459028-7922ed00-55ac-11eb-8e2c-6cb880a091a6.gif)

*Firefox 84.0.2*
![firefox](https://user-images.githubusercontent.com/21216422/104460036-dd927c00-55ad-11eb-9a78-4e3ca0b32a1c.gif)

**macOS Big Sur v11.1**
 
*Firefox 84.0.2*

![firefox](https://user-images.githubusercontent.com/21216422/104459818-91473c00-55ad-11eb-88fa-f7180ccaa43a.gif)

**Comment by plhnk** [comment]
@drakonux to clarify — it looks like you're still able to scroll vertically — IIRC we've hidden the scrollbars as an aesthetic touch (whose merits are definitely up for debate). 

Now that I'm re-reading your comment in the previous issue, it sounds like you're wanting to un-hide the scrollbars?

**Comment by drakonux** [comment]
WOW! So it's done on purpose! I totally disagree hahaha. 

Well just to keep it clear, the mouse cursor and the scrollbars are probably the most idiomatic elements in a digital interface. So it sounds like a risky decision to remove them except doing experimental projects or a super visual thing where the usability is not important. 

Anyway, scrollbars are not only related to the scrolling feature, obviously, they are a hint because they give information that the page is scrollable but they are much more they also tell the user where is on the page and what portion of the page is seeing, which is very useful reading long pages, documentation, and articles! because the user can also go up/down quickly. So I don't see the point of not showing them on the design site which has so much content like that.

Obviously, I want scrollbars on the Lexicon site. Style is not going to be ever over functionality. So, you can close this ticket, I will open a new ticket to implement scrollbars in the Lexicon Site.

**Comment by plhnk** [comment]
Haha thanks @drakonux — it's my bad, something done some time ago without ~any~ enough thought.

I agree completely with your points — we'll fix it globally in this issue, no need to create a separate one just for Lexicon 😅
