### ISSUE TITLE
delete duplicate image at top of article

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#896]
There's a featured image at the top of this article:

https://liferay.design/articles/2019/interview-with-a-designer-b2-b-commerce/

Please delete the second inline image

**Comment by plhnk** [comment]
Can you try doing this [in the CMS](https://liferay.design/admin)? Would be great to see how it handles edits.

**Comment by plhnk** [comment]
fixed in #898! 🎉 🎉🎉

@ryconn888 gets the award for first edit done in the CMS! Your prize money is in the mail sir.
