### ISSUE TITLE
Set order for markdown files

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#90]
**Please describe.**
It's necessary to be able to order the pages

**Describe the solution you'd like**
Possibly using the frontmatter (see [first iteration of blueprints](https://github.com/liferay-design/blueprints/blob/working-file/site/src/pages/docs/about.md))

**Describe alternatives you've considered**
Have not considered alternatives - but open to it?

**Comment by protoEvangelion** [comment]
I got this working and will send a PR soon 😄

**Comment by plhnk** [comment]
[closing per 139 ](https://github.com/liferay-design/liferay.design/pull/139) thanks @protoEvangelion !
