### ISSUE TITLE
GS Diagrams Needs to be Added

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#900]
Rachel made [a great slide deck ](https://docs.google.com/presentation/d/1TahF6vfQlPxs-2A_pup5m05Kqt0_NTcnb_wNrbSMn2s/edit?usp=sharing)for the GS employees to grab the diagrams that are frequently requested. We need this on Blueprints. I think under 'Resources' there probably needs to be another tab that says 'GS Assets'

**Comment by abelhancock** [comment]
Related resources (not sure if they need to be included...):

- [Figma Diagram Kit](https://www.figma.com/file/md4pd0AQswjrSAC4GJ9EeV/diagram-kit?node-id=0%3A1&viewport=236%2C355%2C1)
- [Source File for most diagrams (figma)](https://www.figma.com/file/i1bkFMjkUpjPEfQG0Wdywa/gs-diagrams-assets?node-id=167%3A1930&viewport=519%2C396%2C1)

**Comment by victorvalle** [comment]
@ryconn888 @rachelcyuan should this slide deck should be also under our [google slide templates](https://docs.google.com/presentation/u/0/?ftv=1&tgif=d)

**Comment by victorvalle** [comment]
https://github.com/liferay-design/liferay.design/pull/917

**Comment by plhnk** [comment]
thanks @victorvalle !
