### ISSUE TITLE
Replace Google Analytics

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#902]
**Is your feature request related to a problem? Please describe.**
GA does not respect our users' privacy — additionally it is a decent performance hit.

**Describe the solution you'd like**
Evaluate lightweight, privacy-focused alternatives for analytics.

## Options

1. [Microanalytics](https://microanalytics.io) — has a forever free tier (10k pageviews monthly — our last 90 days of traffic was 11k)
2. [Fathom Analytics](https://usefathom.com) — $14/month, probably one of the best 
3. [Netlify Analytics](https://www.netlify.com/products/analytics/) — $9/month, I used this on my personal site, pretty basic
4. [Cloudflare Analytics](https://www.cloudflare.com/web-analytics/) — similar to netlify, seems more robust

**Comment by plhnk** [comment]
There are a variety of [self-hosted options](dev.to/mokkapps/how-i-replaced-google-analytics-with-a-private-open-source-self-hosted-alternative-5cla) — I believe you can self-host Fathom as well — but it's more involved and probably wouldn't be very cost-effective once we factor in labor.

**Comment by plhnk** [comment]
tangentially related — [Defying the mainstream: building technology that respects our rights](https://noti.st/laurakalbag/firuh2) by Laura Kalbag

**Comment by drakonux** [comment]
_"GA does not respect our user's privacy"_ (I'm curious) How do they do not respect our users' privacy?

**Comment by victorvalle** [comment]
Interesting.

What doors will be open now compared to GA?

What happens if one day we want to include tags to make proper analytics and find out real paths?

**Comment by plhnk** [comment]
> _"GA does not respect our user's privacy"_ (I'm curious) How do they do not respect our users' privacy?

Google's tracking is very invasive, yes theoretically it doesn't identify _you_ personally, but due to their huge reach, their data model creates a profile and its exactly you — your age, gender, familial status, work, times you are working, times you are not, preferences, behavior, on and on and on — because GA is so pervasive on the web, each site that uses it acts as a node to feed this data model. I prefer to not be a node feeding our user's information to this model — especially since so many of our users are our team.

[This seems like content marketing for Fathom](https://www.fastcompany.com/90300072/its-time-to-ditch-google-analytics), so try to ignore that — more consider the downsides of GA.

And to be clear — I haven't gathered an exhaustive case for this, I'm just starting a conversation, [Dave Rupert's post](https://daverupert.com/2019/04/goodbye-google-analytics-hello-fathom/) sums up my feelings at this time:
> Acknowledging my ignorance here, it’s not clear what data I’m contributing to Google’s collective knowledge. I’d rather be more conservative with my own data collection on my site. I also feel the answers I want visualized are buried in Google Analytics. In many ways Google Analytics has grown to become a product that’s overkill for this blog and my needs.

> Interesting.

Thank you @victorvalle 

> What doors will be open now compared to GA?

The doors to easier sleep — you can have a clear conscience knowing our site does not contribute to the Matrix. (Joke — sort of) TBH one of the main value props is better data, easier:

1. Privacy focused analytics actually provide better data on the whole, because they don't get blocked as often (they're not using cookies, ad-blockers don't block them because they aren't an ad platform, etc)
2. Easier to access / read the important stuff — this could just be me — I rarely access GA because there is so much to click through and configure if I want to get some very basic info like pageviews.

> What happens if one day we want to include tags to make proper analytics and find out real paths? 

We should cross that bridge when we get there, not build it and then carry it with us for kilometers and kilometers and kilometers. IMHO this point alone is worth it to remove GA — we are only using a tiny fraction of the cost it adds. Yes, it is "free" , meaning we, and our users, are the product — in addition to that, there is a significant performance hit to using GA and GTM (Google Tag Manager). And IMHO we are only achieving a fraction of the full benefits — so we should consider more using a right-sized tool for our needs.

**Comment by cj213x** [comment]
just reviewed them, seems like microanalytics is the winner
1. it's free
2. supports events analysis. While we cant really do path analysis in any of the choices above, at least we will be able to create goals with events, and not pay like we will with fathom.

**Comment by plhnk** [comment]
@victorvalle @drakonux more thoughts? are we fine to move forward w/our resident analytics/budgetary expert's choice?

**Comment by victorvalle** [comment]
If we can do event analysis I will be happy.
