### ISSUE TITLE
Re-align blueprints homepage w/lexicon

### ISSUE THREAD

**Issue by plhnk** [liferay-design/liferay.design#98]
main differences are in the cards: https://lexicondesign.io

**Comment by phillipchan2** [comment]
I dont understand what's different

**Comment by plhnk** [comment]
@phillipchan2  thanks for asking — the middle card is 🙅 — icon / text placement

also the footer bg is weird, the texture should be attachment:fixed, and there's something strange happening w/the negative margin that causes the image not to render

<img width="2497" alt="screen shot 2018-10-12 at 10 49 33 am" src="https://user-images.githubusercontent.com/10226086/46885495-034bdc00-ce0d-11e8-9a96-0356812bf6fa.png">
<img width="2496" alt="screen shot 2018-10-12 at 10 49 46 am" src="https://user-images.githubusercontent.com/10226086/46885496-03e47280-ce0d-11e8-9484-297a61455e40.png">
